/*
 * Author: Ugwu Rhema
 * Reference wiki.osdev.org, cus this really helped me a lot and also a lot of kernel developers online...
 * ...also helped me to understand the concepts and processes of building a simple monolithic kernel
 * The comments we generated by me so i refernce this source code later
 * Thanks for using BIKT-OS!
 */

#include <stdint.h>
#include <stddef.h> //library for uint32_t and the rest...

//abbreviations to the uint data types
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef struct
{
	u64 base_address;
	u64 length;
	u32 type;	//type 1, usable RAM; type 2, reserved hardware
	u32 acpi_extended;
} __attribute__((packed)) MemoryMapEntry;

#define _BLOCK_SIZE 4096

//place bitmap safely at 1MB, this avoids overwriting the bootloader
static u32 *pmm_bitmap = (u32*)0x100000;
static u32 max_blocks = 0;
static u32 used_blocks = 0;

//inline bit manipulation helper methods...
static inline void bitmap_set(u32 bit)
{
	pmm_bitmap[bit / 32] |= (1 << (bit % 32));
}

static inline void bitmap_clear(u32 bit)
{
	pmm_bitmap[bit / 32] &= ~(1 << (bit % 32));
}

static inline int bitmap_test(u32 bit)
{
	return (pmm_bitmap[bit / 32] & (1 << (bit % 32))) != 0;
}

//sets a range of blocks as free (0)...
void pmm_init_region(u32 base_addr, u32 size)
{
	u32 align = base_addr / _BLOCK_SIZE;
	u32 blocks = size / _BLOCK_SIZE;

	for (; blocks > 0; blocks--)
	{
		bitmap_clear(align++);
		used_blocks--;
	}
}

//sets a range of blocks as used (1)...
void pmm_deinit_region(u32 base_addr, u32 size)
{
	u32 align = base_addr / _BLOCK_SIZE;
	u32 blocks = size / _BLOCK_SIZE;

	for (; blocks > 0; blocks--)
	{
		bitmap_set(align++);
		used_blocks++;
	}
}

//primary PMM(Physical Memory Manager) initialization method...
void pmm_init(u32 memory_entries_count, MemoryMapEntry* mmap_entries)
{
	u64 total_memory = 0;

	//find the highest memory address to calculate how many total blocks needed
	for (u32 i = 0; i < memory_entries_count; ++i)
	{
		if (mmap_entries[i].type == 1)
		{
			u64 end_addr = mmap_entries[i].base_address + mmap_entries[i].length;
			if (end_addr > total_memory)
			{
				total_memory = end_addr;
			}
		}
	}

	max_blocks = (u32)(total_memory / _BLOCK_SIZE);
	used_blocks = max_blocks;

	//by default, mark ALL memory as reserved, set all bits to 1...
	for (u32 i = 0; i < max_blocks / 32; ++i)
	{
		pmm_bitmap[i] = 0xFFFFFFFF;
	}

	//free only the regions marked as type 1(usable) by the BIOS
	for (u32 i = 0; i < memory_entries_count; ++i)
	{
		if (mmap_entries[i].type == 1)
		{
			pmm_init_region((u32)mmap_entries[i].base_address, (u32)mmap_entries[i].length);
		}
	}

	//protect kernel space!
	pmm_deinit_region(0x0000, 0x150000);
}

//finds the first free bit (0) in the bitmap, sets it to one and return the physical address
//since you already know memory alocators return void pointer hehe...
void* pm_alloc_block()
{
	if (max_blocks - used_blocks <= 0) return NULL;

	for (u32 i = 0; i < max_blocks / 32; ++i)
	{
		if (pmm_bitmap[i] != 0xFFFFFFFF) //if this 32 chuck isn't filled(0xFFFFFFFF)
		{
			for (int j = 0; j < 32; j++)
			{
				u32 bit = i * 32 + j;
				if (!bitmap_test(bit))
				{
					bitmap_set(bit);
					used_blocks++;
					return (void*)(bit *_BLOCK_SIZE);
				}
			}
		}
	}
	return NULL;
}

//we have to implement a free to avoid memory leakage...
void pmm_free_block(void* ptr)
{
	u32 addr = (u32)ptr;
	u32 bit = addr / _BLOCK_SIZE;

	bitmap_clear(bit);
 	used_blocks--;
}

//VMM (Virtual Memory Manager), Hardware Paging...

#define _PAGE_PRESENT 0x1 //bit 0: 1 = page is in RAM
#define _PAGE_WRITE 0x2   //bit 1: 1 = Read/write, 0 = Read-Only
#define _PAGE_USER 0x4    //bit 2: 1 = User mode (Ring 3), 0 = Kernel space (Ring 0)

static u32 *kernel_page_directory = NULL;

//maps a specific va(virtual address) to a physical frame address
void vmm_map_page(u32 *page_dir, u32 virtual_addr, u32 physical_addr, u32 flags)
{
	//a 32 bit va contains a 10-bit directory index and a 10-bit table
	u32 dir_index = virtual_addr >> 22;
	u32 table_index = (virtual_addr >> 12) & 0x3FF;

	//check if page table exists for this directory entry
	if (!(page_dir[dir_index] & _PAGE_PRESENT))
	{
		//if it doesnt exist call the PMM to allocate a clear physical frame to a page table entry...
		u32 *new_table = (u32*)pm_alloc_block();

		//zero out the new brand page table
		for (int i = 0; i < 1024; ++i)
		{
			new_table[i] = 0;
		}

		//place physical address of the page table inside the directory entry
		page_dir[dir_index] = (u32)new_table | flags | _PAGE_PRESENT;
	}

	//extract the page table physical address (clearing out lower flags)
	u32 *page_table = (u32*)(page_dir[dir_index] & ~0xFFF);

	page_table[table_index] = physical_addr | flags | _PAGE_PRESENT;
}

void vmm_init()
{
	//allocate a 4KB block from our PMM to serve as MPD(Master Page Directory)
	kernel_page_directory = (u32*)pm_alloc_block();

	//clear out the directory
	for (int i = 0; i < 1024; ++i)
	{
		kernel_page_directory[i] = 0;
	}

	//identity map the first 8MB of memory space
	for (u32 i = 0; i < 0x800000; i += _BLOCK_SIZE)
	{
		vmm_map_page(kernel_page_directory, i, i, _PAGE_WRITE);
	}

	//time to talk to ze hardware assembly lines arrrgh!
	// load base address of out directory layout into ze CPU CR3 register
	__asm__ volatile("mov %0, %%cr3" : : "r"(kernel_page_directory)); //in-line assembly

	//read cr0(control register, remember the register we used to enter PM(Protected Mode))
	//and write it back out
	u32 cr0;
	__asm__ volatile("mov %%cr0, %0" : "=r"(cr0));
	cr0 |= 0x80000000; //toggle the PG Flag bit
	__asm__ volatile("mov %0, %%cr0" : : "r"(cr0));
}

//Heap manipulation hehe
// KMALLOC and KFREE (our own custom memory allocator and memory cleaner (free))

typedef struct Header
{
	struct Header *next;
	u32 size;
	int is_free;
}__attribute__((packed)) Header;

#define _HEAP_START_ADDR 0x1000000 //16 MB virtual boundary
static Header *heap_start = NULL;

void kheap_init(u32 initial_pages)
{
	//Grab continous physical frames from our PMM allocator
	void *phys_start = pm_alloc_block();
	for (u32 i = 1; i < initial_pages; ++i)
	{
		pm_alloc_block();
	}

	//map those pages consecutively into vmemory
	u32 virt = _HEAP_START_ADDR;
	u32 phys = (u32)phys_start;
	for (u32 i = 0; i < initial_pages; ++i)
	{
		vmm_map_page(kernel_page_directory, virt, phys, _PAGE_WRITE);
		virt += _BLOCK_SIZE;
	 	phys += _BLOCK_SIZE;
	}

	//init our first massive free block header...yay!!!
	heap_start = (Header*)_HEAP_START_ADDR;
	heap_start->next = NULL;
	heap_start->size = (initial_pages * _BLOCK_SIZE) - sizeof(Header);
	heap_start->is_free = 1;
}

void* kmalloc(u32 size)
{
	Header* curr = heap_start;

	while(curr)
	{
		if (curr->is_free && curr->size >= size)
		{
			//can we split to presevers leftover space? sure we can!
			if (curr->size >= size + sizeof(Header) + 4)
			{
				Header *new_block = (Header*)((u32)curr + sizeof(Header) + size);
				new_block->next = curr->next;
				new_block->size = curr->size - size - sizeof(Header);
				new_block->is_free = 1;

				curr->next = new_block;
				curr->size = size;
			}	

			curr->is_free = 0;
			//hand back the pointer immediately following the metadata header
			return (void*)((u32)curr + sizeof(Header));
		}
		curr = curr->next;
	}

	return NULL; //only reaches here when heap is exhausted!
}

//free, de-allocate memory in the heap...
void kfree(void *ptr)
{
	if (!ptr) return;

	Header *header = (Header*)((u32)ptr - sizeof(Header));
	header->is_free = 1;

	Header* curr = heap_start;
	while (curr)
	{
		if (curr->is_free && curr->next && curr->next->is_free)
		{
			curr->size += sizeof(Header) + curr->next->size;
			curr->next = curr->next->next;
		}

		curr = curr->next;
	}
}

#define _VGA_ADDRESS 0xB8000 //vga memory address
#define _VGA_COLS 80
#define _VGA_ROWS 25
#define _VGA_ATTR 0x0E //yellow on black

#define _PIC1_COMMAND 0x20
#define _PIC1_DATA    0x21 //master PIC
#define _PIC2_COMMAND 0xA0
#define _PIC2_DATA    0xA1	//slave PIC

#define _ICW1_INIT    0x11
#define _ICW4_8086    0x01

static volatile u16 *vga_buffer = (volatile u16 *)_VGA_ADDRESS;
static long unsigned int cursor_pos = 0;

void pic_remap(void);
void outb(u16 port, u8 val);
void serial_puts(const char* str);
void serial_put_c(char c);
void mouse_wait(u8 type);
void mouse_write(u8 val);
void mouse_init(void);

// Sends a 16-bit word to a hardware port
void outw(u16 port, u16 val) {
    __asm__ volatile ("outw %0, %1" : : "a"(val), "Nd"(port));
}

int strcmp(const char* s1, const char* s2)
{
	while (*s1 && (*s1 == *s2))
	{
		s1++;
		s2++;
	}
	return *(const unsigned char*)s1 - *(const unsigned char*)s2;
}

void memset(void *dest, u8 val, u32 len)
{
	u8* ptr = (u8*)dest;
	while (len--)
	{
		*ptr++ = val;
	}
}

void vga_put_c(char c)
{
	//handle new-line character...
	if (c == '\n')
	{
		cursor_pos = (cursor_pos / _VGA_COLS + 1) * _VGA_COLS;
	} else if (c == '\b'){
		//handling backspace...
		if (cursor_pos > 0)
		{
			cursor_pos--;
			vga_buffer[cursor_pos] = (u16)32 | ((u16)_VGA_ATTR << 8);
		}
	} else {
		//print the char like that if it's not backspace or new-line...
		vga_buffer[cursor_pos] = (u16)c | ((u16)_VGA_ATTR << 8);
		cursor_pos++;
	}
}

//prints text to vga buffer
void vga_puts(const char* str)
{
	while(*str)
	{
		vga_put_c(*str++);
	}
}

void vga_put_num(u32 num)
{
	if (num == 0)
	{
		vga_put_c('0');
		return;
	}
	char buf[12];
	int i = 10;
	buf[11] = '\0';
	while (num > 0 && i >= 0)
	{
		buf[i--] = (num % 10) + '0';
		num /= 10;
	}
	vga_puts(&buf[i + 1]);
}

//this method remaps the entries since long ago the PIC and Exceptions collide...
//...so this maps the PIC IRQs at different addresses from the CPU Exceptions
// Small delay for I/O operations
void io_wait(void) {
    outb(0x80, 0);
}

void pic_remap(void) {
    // Start initialization sequence
    outb(_PIC1_COMMAND, _ICW1_INIT); io_wait();
    outb(_PIC2_COMMAND, _ICW1_INIT); io_wait();

    // Set offsets (Master: 0x20, Slave: 0x28)
    outb(_PIC1_DATA, 0x20); io_wait();
    outb(_PIC2_DATA, 0x28); io_wait();

    // Tell Master there is a slave PIC at IRQ2
    outb(_PIC1_DATA, 4); io_wait();
    // Tell Slave its cascade identity
    outb(_PIC2_DATA, 2); io_wait();

    // Set mode to 8086/88
    outb(_PIC1_DATA, _ICW4_8086); io_wait();
    outb(_PIC2_DATA, _ICW4_8086); io_wait();

    // Mask all interrupts until ready
    outb(_PIC1_DATA, 0xFF); io_wait();
    outb(_PIC2_DATA, 0xFF); io_wait();
}

//outb bytes, sends data to ports/hardware(i guess)
void outb(u16 port, u8 val) {
    __asm__ volatile ("outb %0, %1" : : "a"(val), "Nd"(port));
}

//opposite or outb, reads...
u8 inb(u16 port)
{
	u8 ret;
	__asm__ volatile ("inb %1, %0" : "=a"(ret) : "Nd"(port));
	return ret;
}

//PIC End Of Interrupt, this tells the PIC when an ISR is over...
//...and it should tell CPU to continuw what is was doing "hlt" hehe
void pic_eoi(int irq)
{
	if (irq >= 8) outb(_PIC2_COMMAND, 0x20);
	outb(_PIC1_COMMAND, 0x20);
}

typedef struct {
    u16 offset_low;      // Low 16 bits of handler address
    u16 selector;        // Segment selector(normally 0x08 form our GDT remember?)
    u8 zero;             // Always 0
    u8 type_attr;        // 0x8E = interrupt gate
    u16 offset_high;     // High 16 bits of handler address
} __attribute__((packed)) IDT_Entry;

typedef struct {
    u16 size;            // Size of IDT - 1
    u32 address;         // Address of IDT array
} __attribute__((packed)) IDTR;

#define _IDT_ENTRIES 256
static IDT_Entry idt[_IDT_ENTRIES]; //create the 256 IDT entries

//printf hexadecimal text...
void vga_put_hex(u32 num)
{
    const char *hex = "0123456789ABCDEF";

    vga_puts("0x");

    // Print each hex digit
    for (int i = 7; i >= 0; i--)
    {
        u8 digit = (num >> (i * 4)) & 0xF;
        vga_put_c(hex[digit]);
    }
}

// Function to set one IDT entry
void idt_set_entry(int index, u32 handler_addr, u16 selector, u8 type_attr)
{
    idt[index].offset_low = handler_addr & 0xFFFF;           // Low 16 bits
    idt[index].offset_high = (handler_addr >> 16) & 0xFFFF;  // High 16 bits
    idt[index].selector = selector;
    idt[index].zero = 0;
    idt[index].type_attr = type_attr;
}

// Load IDT into CPU
void idt_load(void)
{
    static IDTR idtr; // Static ensures it stays in memory
    idtr.size = (sizeof(IDT_Entry) * _IDT_ENTRIES) - 1;
    idtr.address = (u32)&idt;

    __asm__ volatile("lidt %0" : : "m"(idtr));
}

//various handlers...
//because of __attribute__((interrupt)) we dont have to make an externel ISR stub
//and it auto returns iret not ret so the CPU knows its an interrupt
__attribute__((interrupt)) void divide_by_zero_handler(void *frame)
{
    vga_puts("\n=== INTERRUPT #0: DIVIDE BY ZERO ===\n");
    vga_puts("A program tried to divide by zero!\n");
    vga_puts("System halted.\n");

    while(1)
    {
        __asm__("hlt");
    }
}

__attribute__((interrupt)) void debug_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #1: DEBUG ===\n");
	vga_puts("Debug exception triggered (breakpoint/single-step).\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void nmi_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #2: NON-MASKABLE INTERRUPT ===\n");
	vga_puts("Hardware error detected!\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void breakpoint_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #3: BREAKPOINT ===\n");
	vga_puts("Breakpoint hit (int3 instruction).\n");
}

__attribute__((interrupt)) void overflow_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #4: OVERFLOW ===\n");
	vga_puts("Signed integer overflow detected!\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void bound_range_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #5: BOUND RANGE EXCEEDED ===\n");
	vga_puts("Array index out of bounds (BOUND instruction).\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void invalid_opcode_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #6: INVALID OPCODE ===\n");
	vga_puts("CPU executed an unknown instruction!\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void device_not_available_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #7: DEVICE NOT AVAILABLE ===\n");
	vga_puts("Floating point unit not enabled or missing.\n");
	while(1) __asm__("hlt");
}

// Double Fault has error code - different signature
__attribute__((interrupt)) void double_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #8: DOUBLE FAULT ===\n");
	vga_puts("Processor couldn't handle another exception!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void invalid_tss_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #10: INVALID TSS ===\n");
	vga_puts("Task state segment is invalid!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void segment_not_present_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #11: SEGMENT NOT PRESENT ===\n");
	vga_puts("Segment descriptor not present in memory!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void stack_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #12: STACK-SEGMENT FAULT ===\n");
	vga_puts("Stack segment violation!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void general_protection_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #13: GENERAL PROTECTION FAULT ===\n");
	vga_puts("Memory protection violation!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void floating_point_exception_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #16: FLOATING POINT EXCEPTION ===\n");
	vga_puts("Math Error in the FPU\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

// Page Fault has error code
__attribute__((interrupt)) void page_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #14: PAGE FAULT ===\n");
	vga_puts("Memory page not present or access violation!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");

	// Read faulting address from CR2 register
	u32 faulting_addr;
	__asm__("mov %%cr2, %0" : "=r"(faulting_addr));
	vga_puts("Faulting address: ");
	vga_put_hex(faulting_addr);
	vga_puts("\n");

	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void alignment_check_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #17: ALIGNMENT CHECK ===\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

__attribute__((interrupt)) void machine_check_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #18: MACHINE CHECK ===\n");
	vga_puts("Fatal hardware error!\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

__attribute__((interrupt)) void simd_floating_point_exception_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #19: SIMD FLOATING-POINT EXCEPTION ===\n");
	vga_puts("Math Error in the SSE/AVX\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

#define _PIT_COMMAND 0x43
#define _PIT_CHANNEL0 0x40

// Configure PIT to fire at a specific frequency (Hz)
void pit_init(u32 frequency) {
    // 1193182 Hz is the internal PIT oscillator frequency
    u32 divisor = 1193182 / frequency;

    // Command byte: Channel 0, access lo/hi byte, square wave mode, 16-bit binary
    // 0x36 = 00110110b
    outb(_PIT_COMMAND, 0x36);

    // Send divisor split across low byte and high byte
    outb(_PIT_CHANNEL0, (u8)(divisor & 0xFF));
    outb(_PIT_CHANNEL0, (u8)((divisor >> 8) & 0xFF));
}

static u32 timer_ticks = 0; //timer ticks...

void sleep(u32 milliseconds)
{
	u32 target_ticks = timer_ticks + milliseconds;

	while (timer_ticks < target_ticks)
	{
		__asm__ volatile("hlt");
	}
}

__attribute__((interrupt)) void timer_handler(void *frame)
{
	timer_ticks++;
	pic_eoi(0);
	//we'll make use of this again when making a sleep() command...
}

//buffer for keyboard buffer (keyboard driver)
#define _BUFFER_SIZE 64

//array of characters for the buffer
char key_buffer[_BUFFER_SIZE];
//keeps track of current buffer status
int buffer_head = 0;
int buffer_tail = 0;

// Add a character to the buffer
void buffer_push(char c) {
    key_buffer[buffer_head] = c;
    buffer_head = (buffer_head + 1) % _BUFFER_SIZE; //increments buffer head
}

// Remove and return a character from the buffer
char buffer_pop(void) {
    if (buffer_head == buffer_tail) return 0; // this'll mean the buffer is empty
    char c = key_buffer[buffer_tail];
    buffer_tail = (buffer_tail + 1) % _BUFFER_SIZE; //increments buffer tail
    return c;
}

//special case keys for the keyboard interrpt and drivers
int shift_pressed = 0;
int caps_lock = 0;
int ctrl_key = 0;

// The index is the scan code. 0 means "no character".
//current characters the CPU can read from the keyboard
const char kdb_map[] = {
    0, 27, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',
    '\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n',
    0, 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', 0, '\\',
    'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 0, '*', 0, ' '
};

__attribute__((interrupt)) void keyboard_handler(void *frame)
{
	u8 scancode = inb(0x60); //read from the keyboard PIC ports

	//detect if it is a break code... (key release)
	if (scancode & 0x80)
	{
		u8 release_code = scancode - 0x80;
		if (release_code == 0x2A || release_code == 0x36) //left & right SHIFT
		{
			shift_pressed = 0;
		}
	}

	//logic if it's not a break code...
	else {
		if (scancode == 0x2A || scancode == 0x36) //left & right SHIFT
		{
			shift_pressed = 1;
		} else if (scancode == 0x3A){
			//caps-lock...
			caps_lock = !caps_lock;
		} else if (scancode == 0x0E){
			//backspace '\b'
			buffer_push('\b');
		} else {
			char c = kdb_map[scancode];
			if (c != 0)
			{
				//if shift is pressed...
				if (shift_pressed && c >= 'a' && c <= 'z')
				{
					//convert to upper-case...
					c -= 32;
				} else if (caps_lock && c >= 'a' && c <='z'){
					//if caps_lock is pressed...
					c -= 32;
				}

				buffer_push(c);
			}
		}
	}
	pic_eoi(1);
}

//the COM1 port handler...
__attribute__((interrupt)) void com1_handler(void *frame)
{
	vga_puts("COM1 Activity!\n");
	pic_eoi(4);
}

//MOUSE INIT, waking up the mouse...
// mouse wait method, to wait for input to be data to be ready or...
// ...input to be empty
void mouse_wait(u8 type)
{
	u32 timeout = 100000;
	if (type == 0) //wait for ready data to be read...
	{
		while (--timeout && !(inb(0x64) & 1));
	} else { //wait for buffer to be empty to write...
		while (--timeout && (inb(0x64) & 2));
	}
}

//writes to the mouse, [data]
void mouse_write(u8 val)
{
	mouse_wait(1); //wait for input to be empty
	outb(0x64, 0xD4); //send to the Mouse PIC port that we wanna write
	mouse_wait(1);
	outb(0x60, val); //send the actual data
}

//initializes the mouse
void mouse_init(void)
{
    u8 status;

    mouse_wait(1);
    outb(0x64, 0xA8); // Enable mouse port

    mouse_wait(1);
    outb(0x64, 0x20); // Read Command Byte
    mouse_wait(0);
    status = inb(0x60);
    status |= 3;      // SET BOTH BIT 0 (Keyboard) AND BIT 1 (Mouse)

    mouse_wait(1);
    outb(0x64, 0x60); // Write Command Byte
    mouse_wait(1);
    outb(0x60, status);

    mouse_write(0xF6); // Set defaults
    mouse_write(0xF4); // Enable data reporting
}

//mouse driver init...
u8 mouse_packet[3];
u8 mouse_cycle = 0; //tracks which byte from 0,1,2 we are on!

__attribute__((interrupt)) void mouse_handler(void *frame)
{
	u8 status = inb(0x64); //read status register to ensure data is ready

	if (status & 0x01) //if there's data to read...
	{
		u8 data = inb(0x60);

		switch (mouse_cycle)
		{
			case 0: //byte 1: status
				mouse_packet[0] = data;
				mouse_cycle = 1;
				break;
			case 1: //byte 2: X-Movement
				mouse_packet[1] = data;
				mouse_cycle = 2;
				break;
			case 2: //byte 3: Y-Movement
				mouse_packet[2] = data;
				mouse_cycle = 0; //Reset for the next packet
				//Here we will process the full packet
				serial_puts("mouse moved!");
				break;
		}
	}
	pic_eoi(12);
}

// Generic interrupt handler
// This handles unexpected interrupts that haven't been mapped yet...
__attribute__((interrupt)) void default_interrupt_handler(void *frame) {
    vga_puts("\n=== UNEXPECTED INTERRUPT ===\n");
    vga_puts("An unexpected interrupt occurred! System halted.\n");
    while(1) {
        __asm__("hlt");
    }
}

//initializees the IDT
void idt_init(void)
{
    __asm__("cli"); //clear interrupts

    vga_puts("Initializing IDT...\n");

    // Clear all IDT entries first and set them to default handler
    for (int i = 0; i < _IDT_ENTRIES; i++)
    {
        // Use 0x8E for interrupt gate, Present bit set, ring 0, interrupt gate
        idt_set_entry(i, (u32)default_interrupt_handler, 0x08, 0x8E);
    }

    // Set up specific handlers (will overwrite default for these)
    idt_set_entry(0, (u32)divide_by_zero_handler, 0x08, 0x8E);
    idt_set_entry(1, (u32)debug_handler, 0x08, 0x8E);
    idt_set_entry(2, (u32)nmi_handler, 0x08, 0x8E);
    idt_set_entry(3, (u32)breakpoint_handler, 0x08, 0x8E);
    idt_set_entry(4, (u32)overflow_handler, 0x08, 0x8E);
    idt_set_entry(5, (u32)bound_range_handler, 0x08, 0x8E);
    idt_set_entry(6, (u32)invalid_opcode_handler, 0x08, 0x8E);
    idt_set_entry(7, (u32)device_not_available_handler, 0x08, 0x8E);
    idt_set_entry(8, (u32)double_fault_handler, 0x08, 0x8E);
    idt_set_entry(10, (u32)invalid_tss_handler, 0x08, 0x8E);
    idt_set_entry(11, (u32)segment_not_present_handler, 0x08, 0x8E);
    idt_set_entry(12, (u32)stack_fault_handler, 0x08, 0x8E);
    idt_set_entry(13, (u32)general_protection_fault_handler, 0x08, 0x8E);
    idt_set_entry(14, (u32)page_fault_handler, 0x08, 0x8E);
    idt_set_entry(16, (u32)floating_point_exception_handler, 0x08, 0x8E);
    idt_set_entry(17, (u32)alignment_check_handler, 0x08, 0x8E);
    idt_set_entry(18, (u32)machine_check_handler, 0x08, 0x8E);
    idt_set_entry(19, (u32)simd_floating_point_exception_handler, 0x08, 0x8E);

    // IRQ handlers (PIC mapped IRQs)
    idt_set_entry(0x20, (u32)timer_handler, 0x08, 0x8E); // IRQ0 - Timer
    idt_set_entry(0x21, (u32)keyboard_handler, 0x08, 0x8E); // IRQ1 - Keyboard
    idt_set_entry(0x24, (u32)com1_handler, 0x08, 0x8E); // IRQ4 - COM1
    idt_set_entry(0x2C, (u32)mouse_handler, 0x08, 0x8E); // IRQ12 - Mouse

    // Load IDT into CPU
    idt_load();
    //__asm__("sti"); //start interrupts
}

//... (rest of the file)

#define _COM1 0x3f8

//starts the serial_driver and it listens...
//..like a radio
void serial_init(void)
{
    // 1. Disable all interrupts (we are doing polling for now)
    outb(_COM1 + 1, 0x00);
    // 2. Enable DLAB (set divisor mode)
    outb(_COM1 + 3, 0x80);
    // 3. Set divisor to 3 (38400 baud)
    outb(_COM1 + 0, 0x03);
    outb(_COM1 + 1, 0x00);
    // 4. 8 bits, no parity, one stop bit
    outb(_COM1 + 3, 0x03);
    // 5. Enable FIFO, clear them, with 14-byte threshold
    outb(_COM1 + 2, 0xC7);
    // 6. IRQs enabled, RTS/DSR set
    outb(_COM1 + 4, 0x0B);
}

//to check if there is 'noise', if there is we can't print
//and we wait for the noise to settle then
int is_transmit_empty(void)
{
	return inb(_COM1 + 5) & 0x20;
}

//prints a character to 0x3f8
void serial_put_c(char c)
{
	while (is_transmit_empty() == 0);
	outb(_COM1, c);
}

//prints text to 0x3f8
void serial_puts(const char* str)
{
	while (*str)
	{
		serial_put_c(*str++);
	}
}

void qemu_shutdown(void) {
    // QEMU newer versions / Bochs ACPI shutdown
    outw(0x604, 0x2000);
    // QEMU older versions (VirtualBox / PCem often support this port too)
    outw(0xB004, 0x2000);
}

#define _SHELL_BUFFER_SIZE  256
char shell_buffer[_SHELL_BUFFER_SIZE];
u32 shell_index = 0;

//main kernel function
void kmain(u32 memory_entries_count, MemoryMapEntry* mmap_entries)
{
	serial_init();     // Ready the serial interface
	pit_init(1000);    // Configure timer ticks to 1ms
	idt_init();        // Set up interrupt handlers silently
	pic_remap();       // Remap PIC away from CPU exception vectors

	// Unmask required hardware interrupt lines
	outb(_PIC1_DATA, 0xF0); // Open Timer (IRQ0), Keyboard (IRQ1), COM1 (IRQ4)
	outb(_PIC2_DATA, 0xEF); // Open Mouse (IRQ12)

	// Bring the kernel to life globally!
	__asm__("sti");

	// Flush old keyboard controller trailing bytes safely
	while (inb(0x64) & 1) {
		inb(0x60);
	}

	serial_puts("Silent core initialization successful. Booting UI...\n");

	vga_puts("BIKT-OS KERNEL v1.0.0 (Unix Like)\n");
	vga_puts("Copyright (c) 2026 Ugwu Rhema.\n");
	vga_puts("\n");
	sleep(400);
	vga_puts("[ OK ] - Initializing GDT and system descriptors...\n");
	sleep(500);
	vga_puts("[ OK ] - Interrupt Descriptor Table (IDT) loaded.\n");
	sleep(400);
	vga_puts("[ OK ] - PIC successfully remapped. Vector offsets: 0x20 / 0x28.\n");
	sleep(600);
	vga_puts("[ INFO ] - Initializing peripheral driver models...\n");
	mouse_init();
	sleep(500);
	vga_puts("[ OK ] - Serial COM1 port driver active.\n");
	sleep(400);
	vga_puts("[ OK ] - i8042 PS/2 Keyboard driver active.\n");
	sleep(400);
	vga_puts("[ OK ] - PS/2 Mouse driver pointer subsystem active.\n");
	sleep(800);
	vga_puts("[ INFO ] - Setting up Physical Memory Management (PMM). \n");
	sleep(500);
	vga_puts("[ INFO ] - Memory Map active. \n");
	sleep(400);
	//start up the monolithic allocator...
	pmm_init(memory_entries_count, mmap_entries);
	vga_puts("[ OK ] - PMM Monolithic Allocator Active. \n");
	sleep(600);
	vga_puts("[ INFO ] - Constructing kernel tables and activating paging. \n");
	sleep(500);
	vmm_init();
	vga_puts("[ OK ] - Virtual Memory Manager (VMM) Active. Paging Enabled. \n");
	sleep(400);
	vga_puts("[ INFO ] - Shaping out Kernel Heap Space. \n");
	sleep(400);
	kheap_init(32);	//map a 128 KB initail heap space (32 pages)
	vga_puts("[ OK ] - Kernel Heap Active (kmalloc & kfree enabled). \n");
	sleep(800);
	vga_puts("\nSetting of all essesntials done, Launching user session in 3 seconds...\n");
	sleep(3000);


	//CLI here broski....
	//clear screen...
	cursor_pos = 0;
	volatile u16 *vga = (volatile u16 *)_VGA_ADDRESS;
    for (int i = 0; i < _VGA_COLS * _VGA_ROWS; i++) {
        vga[i] = (u16)' ' | ((u16)_VGA_ATTR << 8);
    }

    vga_puts("Welcome to the BIKT_OS CLI(Command Line Interface)\n");
    vga_puts("Type 'help' foe a list of helpful commands\n");

    vga_puts("===========\n");
    vga_puts("||        \\\n");
    vga_puts("||         ||\n");
    vga_puts("||        //\n");
    vga_puts("===========\n");
    vga_puts("||         \\\n");
    vga_puts("||          ||\n");
    vga_puts("||         //\n");
    vga_puts("===========\n\n");

	//initail prompt
	vga_puts("@root:bikt_os> ");
	serial_puts("@root:bikt_os> ");

	memset(shell_buffer, 0, _SHELL_BUFFER_SIZE);

	while (1)
	{
		char c = buffer_pop();

		if (c != 0)
		{
			//Handle enter key...
			if (c == '\n')
			{
				vga_put_c('\n');

				shell_buffer[shell_index] = '\0'; //null-terminate the string

				//command parser...
				if (shell_index > 0)
				{
					if (strcmp(shell_buffer, "help") == 0)
					{
						vga_puts("Commands currently available: \n\n");
						vga_puts("help| exit | whereami | fetch | clear | ping | wifi| mem\n");
						vga_puts("mmap|whoami| alloc_test\n");
					} else if (strcmp(shell_buffer, "clear") == 0){
						// Quick screen clear: reset cursor and wipe VGA memory space
                    	extern long unsigned int cursor_pos; // access your global cursor tracking
                     	cursor_pos = 0;
                      	volatile u16 *vga = (volatile u16 *)0xB8000;
                       	for (int i = 0; i < 80 * 25; i++) {
                        	vga[i] = (u16)' ' | ((u16)0x0E << 8);
                        }

					} else if (strcmp(shell_buffer, "ping") == 0){
						vga_puts("pong!\n");
					} else if (strcmp(shell_buffer, "whoami") == 0){
						vga_puts("root\n");
					} else if (strcmp(shell_buffer, "mmap") == 0){
						vga_puts("Type: 1=Usable RAM | 2=Reserved Hardware\n");
						vga_puts("BASE-ADDRESS------LENGTH------TYPE\n");
						vga_puts("__________________________________\n");

						u32 lines_printed = 0;

						for (u32 i = 0; i < memory_entries_count; ++i)
						{
							if (lines_printed > 0 && lines_printed % 10 == 0)
							{
								vga_puts("\n-- Press ANY key for entries --");

								while (buffer_pop() != 0);

								char wait_char = 0;
								while (wait_char == 0)
								{
									__asm__ volatile("hlt"); //rest CPU safely
									wait_char = buffer_pop();
								}

								for (int b = 0; b < 31; b++)
								{
									vga_put_c('\b');
								}
							}
							//prints base address
							vga_put_hex((u32)mmap_entries[i].base_address);
							vga_puts("------");

							//prints length
							vga_put_hex((u32)mmap_entries[i].length);
							vga_puts("------");

							if (mmap_entries[i].type == 1)
							{
								vga_puts("1 (Usable)\n");
							} else {
								vga_puts("2 (Reserved)\n");
							}

							lines_printed++;
						}
					} else if (strcmp(shell_buffer, "mem") == 0){
						u32 actual_free_blocks = 0;

					    // Manually count the actual 0 bits
					    for (u32 i = 0; i < max_blocks; i++) {
					        if (!bitmap_test(i)) {
					            actual_free_blocks++;
					        }
					    }
					
					    u32 free_mb = actual_free_blocks / 256;
					    u32 total_mb = max_blocks / 256;
					
					    vga_puts("PMM Stats:\n");
					    vga_puts("  Total Tracked Address Space: ");
					    vga_put_num(total_mb);
					    vga_puts(" MB\n");
					
					    vga_puts("  Actual Free Usable RAM:      ");
					    vga_put_num(free_mb);
					    vga_puts(" MB\n");
					} else if (strcmp(shell_buffer, "sleep") == 0 ){
						vga_puts("Sleeping for 2 Seconds\n");
						sleep(2000);
					} else if (strcmp(shell_buffer, "fetch") == 0){
						vga_puts("\nBIKT-OS KERNEL version 1.0.0\n");
						vga_puts("Shell: /bin/bish (Bikt Integrated SHell)\n");
						vga_puts("===========\n");
						vga_puts("||        \\\n");
						vga_puts("||         ||\n");
						vga_puts("||        //\n");
						vga_puts("===========\n");
						vga_puts("||         \\\n");
						vga_puts("||          ||\n");
						vga_puts("||         //\n");
						vga_puts("===========\n\n");
					} else if (strcmp(shell_buffer, "wifi") == 0){
						vga_puts("wifi connected\n");
					} else if (strcmp(shell_buffer, "exit") == 0){
						vga_puts("Shutting down BIKT-OS safely...\n");
						serial_puts("Shutdown command executed via CLI. Halting system.\n");

						// 1. Wait a moment for visual feedback
						sleep(1000);

						// 2. Try QEMU/Emulator explicit shutdown ports
						qemu_shutdown();

						// 3. Fallback: If running on real hardware (where port 0x604 does nothing),
						// turn off interrupts and lock the CPU in a dead loop so it's safe to power off.
						vga_puts("It is now safe to turn off your computer.\n");
						__asm__ volatile("cli"); // Disable interrupts so the clock timer stops waking it up
						while(1) {
							__asm__ volatile("hlt"); // Put CPU into deep sleep forever
						}
					} else if (strcmp(shell_buffer, "alloc-test") == 0){
						vga_puts("Testing Heap...Allocating Memory blocks:\n");
						sleep(1000);

						char *ptr1 = (char*)kmalloc(128);
						char *ptr2 = (char*)kmalloc(128);

						vga_puts("  Block 1 Allocated at address: 0x");
						vga_put_num((u32)ptr1);
						vga_puts("\n");

						vga_puts("  Block 2 Allocated at address: 0x");
						vga_put_num((u32)ptr2);
						vga_puts("\n");

						sleep(1000);
						
						if (ptr1 && ptr2)
						{
							vga_puts("[ OK ] - Splitting and headers intact, freeing...\n");
							kfree(ptr1);
							kfree(ptr2);
							vga_puts("[ SUCCESS ] - Memory freed and Heap Stable. \n");
						} else {
							vga_puts("[ ERROR ] - Allocation failed! Retruned NULL. \n");
						}
					} else if (strcmp(shell_buffer, "whereami") == 0){
						vga_puts("you are in root!\n");
					} else {
						vga_puts("/bin/bish: unknown command: ");
						vga_puts(shell_buffer);
						vga_puts("\n");
					}
				}

				//reset shell for next command...
				memset(shell_buffer, 0, _SHELL_BUFFER_SIZE);
				shell_index = 0;

				vga_puts("\n@root:bikt_os> ");
				serial_puts("\n@root:bikt_os> ");
			} else if (c == '\b'){
				//handle backspace key...
				if (shell_index > 0)
				{
					shell_index--;
					shell_buffer[shell_index] = 0;

					//trigger visual backspace deletion on VGA
					vga_put_c('\b');
				}
			} else {
				//handle regular characters...
				if (shell_index < _SHELL_BUFFER_SIZE - 1)
				{
					shell_buffer[shell_index] = c;
					shell_index++;

					vga_put_c(c);
					serial_put_c(c);
				}
			}
		}

		__asm__("hlt"); //rest CPU until next interrupt!
	}

	/*//halt the CPU forever after executing instructions...
	is what we would've continued doing until we got our
	keyboard and mouse drivers working, so why don't we make a CLI
	above!
	while(1){
		char c = buffer_pop();
		if (c != 0)
		{
			vga_put_c(c);
			serial_put_c(c);
		}
		__asm__("hlt");
	}
*/
}

//IT WAS PERFECT!
