/*
 * Author: Ugwu Rhema
 * Reference wiki.osdev.org, cus this really helped me a lot and also a lot of kernel developers online...
 * ...also helped me to understand the concepts and processes of building a simple monolithic kernel
 * The comments we generated by me so i refernce this source code later
 * Thanks for using UROS!
 */

//#include <ctype.h>
#include <stdint.h>
#include <stddef.h> //library for uint32_t and the rest...

//abbreviations to the uint data types
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int32_t i32;
typedef int64_t i64;

int strcmp(const char* s1, const char* s2);
void vga_puts(const char* str);
void vga_put_c(char c);
int ata_identify_slave(void);
void ata_read_sector(u32 lba, u8* buffer);
void ata_write_sector(u32 lba, u8* buffer);
void vga_put_hex(u32 num);
void vga_put_num(u32 num);
void memset(void *dest, u8 val, u32 len);

i32 string_to_int(const char* str)
{
	i32 result = 0;
	i32 sign = 1; //numbers are positive by default

	//skip whitespace
	while (*str == ' ' || *str == '\t' || *str == '\n')
	{
		str++;
	}

	//handle sign
	if (*str == '-')
	{
		sign = -1;
		str++;
	} else if (*str == '+'){
		str++;
	}

	//main conversion
	while (*str >= '0' && *str <= '9')
	{
		result = result * 10 + (*str - '0');
		str++;
	}

	return result * sign;
}

static int str_has_prefix(const char* str, const char *prefix)
{
    while (*prefix)
    {
        if (*prefix != *str) return 0;
        prefix++;
        str++;
    }
    return 1;
}

/* VFS & FAT32 Structs */
typedef struct vfs_node vfs_node_t;

typedef u32 (*vfs_read_type)(vfs_node_t* node, u32 offset, u32 size, u8* buffer);
typedef u32 (*vfs_write_type)(vfs_node_t* node, u32 offset, u32 size, u8* buffer);
typedef void (*vfs_open_type)(vfs_node_t* node);
typedef void (*vfs_close_type)(vfs_node_t* node);
typedef vfs_node_t* (*vfs_readdir_type)(vfs_node_t* node, u32 index);
typedef vfs_node_t* (*vfs_finddir_type)(vfs_node_t* node, const char* name);

struct vfs_node {
	char name[128];
	u32 type;
	u32 size;
	u32 inode;
	vfs_read_type read;
	vfs_write_type write;
	vfs_open_type open;
	vfs_close_type close;
	vfs_readdir_type readdir;
	vfs_finddir_type finddir;
	struct vfs_node* ptr;
};

typedef struct __attribute__((packed)) {
	u8 bootjmp[3];
	u8 oem_name[8];
	u16 bytes_per_sector;
	u8 sectors_per_cluster;
	u16 reserved_sector_count;
	u8 num_fats;
	u16 root_entry_count;
	u16 total_sectors_16;
	u8 media_type;
	u16 fat_size_16;
	u16 sectors_per_track;
	u16 num_heads;
	u32 hiden_sectors;
	u32 total_sectors_32;
	u32 fat_size_32;
	u16 ext_flags;
	u16 fs_version;
	u32 root_cluster;
	u16 fs_info;
	u16 backup_boot_sector;
	u8 reserved[12];
	u8 drive_number;
	u8 nt_reserved;
	u8 boot_signature;
	u32 volume_id;
	u8 volume_label[11];
	u8 fs_type[8];
} FAT32_BPB;

typedef struct __attribute__((packed)) {
	u8 name[11];
	u8 attr;
	u8 nt_res;
	u8 crt_time_ten;
	u16 crt_time;
	u16 crt_date;
	u16 lst_ac_date;
	u16 first_cluster_hi;
	u16 wrt_time;
	u16 wrt_date;
	u16 first_cluster_lo;
	u32 file_size;
} FAT32_DirEntry;

typedef struct
{
	u8 bootable; //0x80 = active boot partition, 0x00 = inactive
	u8 start_head;
	u8 start_sec : 6;
	u16 start_cyl : 10; //packed CHS geometrics
	u8 part_type; //0x0B or 0x0C for FAT32
	u8 end_head;
	u8 end_sec : 6;
	u16 end_cyl : 10;
	u32 lba_start; //crucial: the absolute starting sector address on disk!
	u32 num_sectors; //total sector count of this partition volume
} __attribute__((packed)) MBR_PartitionEntry;

typedef struct
{
	u8 bootstrap[446]; //core assembly master boot bootstrap code area
	MBR_PartitionEntry partitions[4];
	u16 boot_signature; //you know the usual 0xAA55...
} __attribute__((packed)) MBR_Sector;

//global tracking register to store where our fat32 volume actually begins
static u32 partition_offset = 0;

/* VFS & FAT32 Function Prototypes */
u32 vfs_read(vfs_node_t *node, u32 offset, u32 size, u8 *buffer);
u32 vfs_write(vfs_node_t *node, u32 offset, u32 size, u8* buffer);
vfs_node_t* vfs_find_path(vfs_node_t *root, const char *path);
void vfs_init(int mount_hardware);
int fat32_init(void);
u32 fat32_cluster_to_sector(u32 cluster);
int fat32_compare_name(const char* input_name, const u8* fat_name);
struct vfs_node *fat32_finddir(struct vfs_node *dir_node, const char* name);
vfs_node_t* mock_root_finddir(vfs_node_t* node, const char* name);
vfs_node_t* mock_bin_finddir(vfs_node_t* node, const char* name);
u32 mock_file_read(vfs_node_t* node, u32 offset, u32 size, u8* buffer);
u32 fat32_read(struct vfs_node *node, u32 offset, u32 size, u8 *buffer);
u32 fat32_write(struct vfs_node *node, u32 offset, u32 size, u8 *buffer);
void format_fat_name(const char* src, u8* dest);
void fat32_write_fat_entry(u32 cluster, u32 value);
u32 fat32_find_free_cluster(void);
int fat32_create_dir(u32 parent_cluster, const char* dirname);
int fat32_add_entry(u32 dir_cluster, const char* filename, u8 attrib, u32 starting_cluster, u32 file_size);
void fat32_sync_directory_metadata(vfs_node_t *file_node, u32 parent_dir_cluster, u32 newsize, u32 first_cluster);

typedef struct
{
	u64 base_address;
	u64 length;
	u32 type;	//type 1, usable RAM; type 2, reserved hardware
	u32 acpi_extended;
} __attribute__((packed)) MemoryMapEntry;

#define _BLOCK_SIZE 4096

//place bitmap safely at 1MB, this avoids overwriting the bootloader
static u32 *pmm_bitmap = (u32*)0x100000;
static u32 max_blocks = 0;
static u32 used_blocks = 0;

//inline bit manipulation helper methods...
static inline void bitmap_set(u32 bit)
{
	pmm_bitmap[bit / 32] |= (1 << (bit % 32));
}

static inline void bitmap_clear(u32 bit)
{
	pmm_bitmap[bit / 32] &= ~(1 << (bit % 32));
}

static inline int bitmap_test(u32 bit)
{
	return (pmm_bitmap[bit / 32] & (1 << (bit % 32))) != 0;
}

//sets a range of blocks as free (0)...
void pmm_init_region(u32 base_addr, u32 size)
{
	u32 align = base_addr / _BLOCK_SIZE;
	u32 blocks = size / _BLOCK_SIZE;

	for (; blocks > 0; blocks--)
	{
        u32 bit = align++;
        //only decrement if the page frame waas previously marked as used
        if (bitmap_test(bit))
        {
            bitmap_clear(bit);
            used_blocks--;
        }
	}
}

//sets a range of blocks as used (1)...
void pmm_deinit_region(u32 base_addr, u32 size)
{
	u32 align = base_addr / _BLOCK_SIZE;
	u32 blocks = size / _BLOCK_SIZE;

	for (; blocks > 0; blocks--)
	{
        u32 bit = align++;
        //only increment counter if the page frame was previously marked as free
		if (!bitmap_test(bit))
        {
            bitmap_set(bit);
		    used_blocks++;
	    }
    }
}

//primary PMM(Physical Memory Manager) initialization method...
void pmm_init(u32 memory_entries_count, MemoryMapEntry* mmap_entries)
{
	u64 total_memory = 0;

	//find the highest memory address to calculate how many total blocks needed
	for (u32 i = 0; i < memory_entries_count; ++i)
	{
		if (mmap_entries[i].type == 1)
		{
			u64 end_addr = mmap_entries[i].base_address + mmap_entries[i].length;
			if (end_addr > total_memory)
			{
				total_memory = end_addr;
			}
		}
	}

	max_blocks = (u32)(total_memory / _BLOCK_SIZE);
	used_blocks = max_blocks;

    u32 bitmap_dwords = (max_blocks + 31) / 32;

	//by default, mark ALL memory as reserved, set all bits to 1...
	for (u32 i = 0; i < bitmap_dwords; ++i)
	{
		pmm_bitmap[i] = 0xFFFFFFFF;
	}

	//free only the regions marked as type 1(usable) by the BIOS
	for (u32 i = 0; i < memory_entries_count; ++i)
	{
		if (mmap_entries[i].type == 1)
		{
			pmm_init_region((u32)mmap_entries[i].base_address, (u32)mmap_entries[i].length);
		}
	}

	//protect kernel space!
	pmm_deinit_region(0x0000, 0x150000);
}

//finds the first free bit (0) in the bitmap, sets it to one and return the physical address
//since you already know memory alocators return void pointer hehe...
void* pm_alloc_block()
{
	if (max_blocks - used_blocks <= 0) return NULL;

    u32 bitmap_dwords = (max_blocks + 31) / 32;
	for (u32 i = 0; i < bitmap_dwords; ++i)
	{
		if (pmm_bitmap[i] != 0xFFFFFFFF) //if this 32 chuck isn't filled(0xFFFFFFFF)
		{
			for (int j = 0; j < 32; j++)
			{
				u32 bit = i * 32 + j;
                if (bit >= max_blocks) return NULL; //do ont allocate beyomd physics
			
                if (!bitmap_test(bit))
                {
                    bitmap_set(bit);
                    used_blocks++;
                    return (void*)(bit * _BLOCK_SIZE);
                }
            }
		}
	}
	return NULL;
}

//we have to implement a free to avoid memory leakage...
void pmm_free_block(void* ptr)
{
	u32 addr = (u32)ptr;
	u32 bit = addr / _BLOCK_SIZE;

	bitmap_clear(bit);
 	used_blocks--;
}

//VMM (Virtual Memory Manager), Hardware Paging...

#define _PAGE_PRESENT 0x1 //bit 0: 1 = page is in RAM
#define _PAGE_WRITE 0x2   //bit 1: 1 = Read/write, 0 = Read-Only
#define _PAGE_USER 0x4    //bit 2: 1 = User mode (Ring 3), 0 = Kernel space (Ring 0)

static u32 *kernel_page_directory = NULL;

static inline void tlb_flush_single(u32 virt_addr)
{
    __asm__ volatile("invlpg (%0)" :: "r"(virt_addr) : "memory");
}

//maps a specific va(virtual address) to a physical frame address
void vmm_map_page(u32 *page_dir, u32 virtual_addr, u32 physical_addr, u32 flags)
{
	//a 32 bit va contains a 10-bit directory index and a 10-bit table
	u32 dir_index = virtual_addr >> 22;
	u32 table_index = (virtual_addr >> 12) & 0x3FF;

	//check if page table exists for this directory entry
	if (!(page_dir[dir_index] & _PAGE_PRESENT))
	{
		//if it doesnt exist call the PMM to allocate a clear physical frame to a page table entry...
		u32 *new_table = (u32*)pm_alloc_block();

		//zero out the new brand page table
		for (int i = 0; i < 1024; ++i)
		{
			new_table[i] = 0;
		}

		//place physical address of the page table inside the directory entry
		page_dir[dir_index] = (u32)new_table | flags | _PAGE_PRESENT;
	}

	//extract the page table physical address (clearing out lower flags)
	u32 *page_table = (u32*)(page_dir[dir_index] & ~0xFFF);

	page_table[table_index] = physical_addr | flags | _PAGE_PRESENT;

    tlb_flush_single(virtual_addr);
}

void vmm_init()
{
	//allocate a 4KB block from our PMM to serve as MPD(Master Page Directory)
	kernel_page_directory = (u32*)pm_alloc_block();

	//clear out the directory
	for (int i = 0; i < 1024; ++i)
	{
		kernel_page_directory[i] = 0;
	}

	//identity map the first 8MB of memory space
	for (u32 i = 0; i < 0x800000; i += _BLOCK_SIZE)
	{
		vmm_map_page(kernel_page_directory, i, i, _PAGE_WRITE);
	}

	//time to talk to ze hardware assembly lines arrrgh!
	// load base address of out directory layout into ze CPU CR3 register
	__asm__ volatile("mov %0, %%cr3" : : "r"(kernel_page_directory)); //in-line assembly

	//read cr0(control register, remember the register we used to enter PM(Protected Mode))
	//and write it back out
	u32 cr0;
	__asm__ volatile("mov %%cr0, %0" : "=r"(cr0));
	cr0 |= 0x80000000; //toggle the PG Flag bit
	__asm__ volatile("mov %0, %%cr0" : : "r"(cr0));
}

//Heap manipulation hehe
// KMALLOC and KFREE (our own custom memory allocator and memory cleaner (free))

typedef struct Header
{
	struct Header *next;
	u32 size;
	int is_free;
}__attribute__((packed)) Header;

#define _HEAP_START_ADDR 0x1000000 //16 MB virtual boundary
static Header *heap_start = NULL;

void kheap_init(u32 initial_pages)
{
    u32 virt = _HEAP_START_ADDR;

    for (u32 i = 0; i < initial_pages; ++i)
    {
        void* phys = pm_alloc_block();
        if (!phys)
        {
            //memory allocation failure
            return;
        }
        vmm_map_page(kernel_page_directory, virt, (u32)phys, _PAGE_WRITE | _PAGE_PRESENT);
        virt += _BLOCK_SIZE; //addvance virtual address sequentially
    }

    heap_start = (Header*)_HEAP_START_ADDR;
    heap_start->next = NULL;
    heap_start->size = (initial_pages * _BLOCK_SIZE) - sizeof(Header);
    heap_start->is_free = 1;
}

void* kmalloc(u32 size)
{
	Header* curr = heap_start;

	while(curr)
	{
		if (curr->is_free && curr->size >= size)
		{
			//can we split to presevers leftover space? sure we can!
			if (curr->size >= size + sizeof(Header) + 4)
			{
				Header *new_block = (Header*)((u32)curr + sizeof(Header) + size);
				new_block->next = curr->next;
				new_block->size = curr->size - size - sizeof(Header);
				new_block->is_free = 1;

				curr->next = new_block;
				curr->size = size;
			}

			curr->is_free = 0;
			//hand back the pointer immediately following the metadata header
			return (void*)((u32)curr + sizeof(Header));
		}
		curr = curr->next;
	}

	return NULL; //only reaches here when heap is exhausted!
}

//free, de-allocate memory in the heap...
void kfree(void *ptr)
{
	if (!ptr) return;

	Header *header = (Header*)((u32)ptr - sizeof(Header));
	header->is_free = 1;

	Header* curr = heap_start;
	while (curr)
	{
		if (curr->is_free && curr->next && curr->next->is_free)
		{
            //merge next bock into current block, for example block A and B
			curr->size += sizeof(Header) + curr->next->size;
			curr->next = curr->next->next;
		} else {
            curr = curr->next;
        }
	}
}

#define _VFS_FILE 0x01
#define _VFS_DIRECTORY 0x02
#define _VFS_DEVICE 0x03

//the global anchor of our system directory tree
static vfs_node_t *vfs_root = NULL;

//VFS core API wrappers...
u32 vfs_read(vfs_node_t *node, u32 offset, u32 size, u8 *buffer)
{
	if (node && node->read)
	{
		//execute the function adress stored inside this specific node
		return node->read(node, offset, size, buffer);
	}

	return 0;
}

//is this correctly implemented?
u32 vfs_write(vfs_node_t *node, u32 offset, u32 size, u8* buffer)
{
	if (node && node->write)
	{
		return node->write(node, offset, size, buffer);
	}
	return 0;
}

//recursively walk path components...
vfs_node_t* vfs_find_path(vfs_node_t *root, const char *path)
{
	if (!root || !path || path[0] != '/') return NULL;
	if (path[1] == '\0') return root;

	char element[128];
	u32 p_idx = 1; //skip the leading root slash
	vfs_node_t *current_node = root;

	while (path[p_idx] != '\0')
	{
		u32 e_idx = 0;
		//parse out individual folder/file names between slashes
		while (path[p_idx] != '/' && path[p_idx] != '\0')
		{
			if(e_idx < 127)
			{
				element[e_idx++] = path[p_idx];
			}
			p_idx++;
		}
		element[e_idx] = '\0';

		if (path[p_idx] == '/') p_idx++;

		if (current_node->finddir)
		{
			//ASK the current directory node to look up the parsed element string
			current_node = current_node->finddir(current_node, element);
			if (!current_node) return NULL; //Not found!
		} else {
			return NULL; //hit a file instead of a folder directory
		}
	}
	return current_node;
}

static FAT32_BPB *mounted_bpb = NULL;
static u32 fat_start_sector = 0;
static u32 data_start_sector = 0;

static char current_working_dir[256] = "/";
static u32 current_dir_cluster = 2; //defaultt fallback to Cluster 2, FAT32 standard root

//a simple in-memory test driver
static vfs_node_t* mock_bin_dir = NULL;
static vfs_node_t* mock_test_file = NULL;

//this function matches 'vfs_finddir_type' signature perfectly!
vfs_node_t* mock_root_finddir(vfs_node_t* node, const char* name)
{
	if (strcmp(name, "bin") == 0) return mock_bin_dir;
	return NULL;
}

//this function matches the 'vfs_finddir_type' signature perfectly!
vfs_node_t* mock_bin_finddir(vfs_node_t* node, const char* name)
{
	if (strcmp(name, "hello.txt") == 0) return mock_test_file;
	return NULL;
}

//this function matches 'vfs_read_type' signature perfectly!
u32 mock_file_read(vfs_node_t* node, u32 offset, u32 size, u8* buffer)
{
	const char *text = "UROS Node System is Cooking Live!";
	u32 len = 0;
	while (text[len]) len++; //simple length check

	if (offset >= len) return 0;
	if (offset + size > len) size = len - offset;

	//copy out the raw memory string payload
	for (u32 i = 0; i  < size; ++i)
	{
		buffer[i] = (u8)text[offset + i];
	}
	return size;
}

void vfs_init(int mount_hardware)
{
	// 1. Allocate root container directory dynamically on the heap
	vfs_root = (vfs_node_t*)kmalloc(sizeof(vfs_node_t));
	vfs_root->type = _VFS_DIRECTORY;

	if (mount_hardware)
	{
		vga_puts("[ VFS ] - Mounting raw IDE storage system to '/'...\n");

		vga_puts("[ VFS ] - Querying hardware storage systems... \n");

		if (fat32_init())
		{
			vga_puts("[ OK ] - FAT32 Volume mapped successfully to '/' \n");
			vfs_root->type = 0x02;  //uses the real field
			vfs_root->inode = mounted_bpb->root_cluster;
			vfs_root->size = 0;
			vfs_root->finddir = fat32_finddir;
			vfs_root->write = fat32_write;
			
			//initialize out tracking state to the actual drive's root cluster
			current_dir_cluster = mounted_bpb->root_cluster;
		} else {
			vga_puts("[ ERROR ] - FAT32 initialization failed falling back to RAM LAyouts. \n");
			mount_hardware = 0; //flip flag to trigger RAM fallback
		}
	}
	else
	{
		vga_puts("[ VFS ] - No hardware mounted. Seeding RAM-backed file node arrays...\n");
		vfs_root->finddir = mock_root_finddir; // Hook up memory lookups!

		// 2. Allocate our virtual /bin folder
		mock_bin_dir = (vfs_node_t*)kmalloc(sizeof(vfs_node_t));
		mock_bin_dir->type = _VFS_DIRECTORY;
		mock_bin_dir->finddir = mock_bin_finddir;

		// 3. Allocate a mock text file inside the heap area
		mock_test_file = (vfs_node_t*)kmalloc(sizeof(vfs_node_t));
		mock_test_file->type = _VFS_FILE;
		mock_test_file->read = mock_file_read;
	}
}

int fat32_init(void)
{
	//allocate a 512 byte buffer on the heap to store the sector data
	u8 *sector_buffer = (u8*)kmalloc(512);
	if (!sector_buffer)
	{
		vga_puts("[ FAT32 ] - Heap allocation failed for sector buffer. \n");
		return 0;
	}

	//read sector 0 (the boot sector) from our primary slave IDE disk
	ata_read_sector(0, sector_buffer);

	//safety check, verify the boot signature (0xaa55)
	u16 boot_signature = *(u16*)(sector_buffer + 510);
	if (boot_signature != 0xAA55)
	{
		vga_puts("[ FAT32 ERROR ] - Sector 0 boot signature invalid, Found: ");
		vga_put_hex(boot_signature);
		vga_puts("\n");
		kfree(sector_buffer);
		return 0;
	}

	//detect idf sector 0 is an MBR or directly the VBR(Volume Boot Record)
	//valid FAT filesystems always begin with an assembly jump instruction (0xEB or 0xE9)
	u8 first_byte = sector_buffer[0];
	u32 target_sector = 0;

	if (first_byte != 0xEB && first_byte != 0xE9)
	{
		vga_puts("[ MBR ] - Partition Table structure detected inside Sector 0. \n");
		MBR_Sector *mbr = (MBR_Sector*)sector_buffer;
		int found_partition = 0;

		for (int i = 0; i < 4; i++)
		{
			//check fot FAT32 Type Identifiers (0x0B = CHS, 0x0C = LBS mapped)
			if (mbr->partitions[i].part_type == 0x0B || mbr->partitions[i].part_type == 0x0C)
			{
				target_sector = mbr->partitions[i].lba_start;
				vga_puts("      Found valid FAT32 partition at LBA Sector: ");
				vga_put_num(target_sector);
				vga_puts("\n");
				found_partition = 1;
				break;
			}
		}

		if (!found_partition)
		{
			vga_puts("[ MBR ERROR ] - No valid FAT32 Volumes found in the partition table. \n");
			kfree(sector_buffer);
			return 0;
		}
	} else {
		vga_puts("[ VBR ] - Flat image layout detected. Sector 0 matches a raw VBR entry directly. \n");
		target_sector = 0;
	}

	//set our absolute volume baseline sector positioning point
	partition_offset = target_sector;

	//load the genuine filesystem descriptor block (VBR) from the computed offset
	ata_read_sector(partition_offset, sector_buffer);
	mounted_bpb = (FAT32_BPB*)sector_buffer;

	boot_signature = *(u16*)(sector_buffer + 510);
	if (boot_signature != 0xAA55)
	{
		vga_puts("[ FAT32 ERROR ] - VBR block verification signature failed! \n");
		kfree(sector_buffer);
		return 0;
	}

	vga_puts("[ FAT32 ] - Mounting media filesystem volumes...\n");
	vga_puts("      OEM Label: ");
	for (int i = 0; i < 8; ++i) vga_put_c(mounted_bpb->oem_name[i]);
	vga_puts("\n");

	//calculate core cluster offset boundaries
	// the File Allocation Table(FAT) starts right after the reserved sectors
	fat_start_sector = mounted_bpb->reserved_sector_count;

	//the data region starts after the reserved sectors and all copies of the FAT tables
	data_start_sector = mounted_bpb->reserved_sector_count + (mounted_bpb->num_fats * mounted_bpb->fat_size_32);
	vga_puts("      Sectors Per Cluster: ");
	vga_put_num(mounted_bpb->sectors_per_cluster);
	vga_puts("\n      FAT Start Sector: ");
	vga_put_num(fat_start_sector);
	vga_puts("\n      Data Region Start: ");
	vga_put_num(data_start_sector);
	vga_puts("\n");

	return 1; //successfully mounted!
}

u32 fat32_read(struct vfs_node *node, u32 offset, u32 size, u8 *buffer)
{
	if (!node || mounted_bpb == NULL || size == 0) return 0;

	//safety constraint: clamp readinf bounds file size
	if (offset >= node->size) return 0;
	if (offset + size > node->size) size = node->size - offset;

	u32 bytes_per_cluster = mounted_bpb->sectors_per_cluster * 512;
	u32 start_cluster = node->inode;

	//skip clusters if the read offset is deeper than cluster 0
	u32 cluster_skip = offset / bytes_per_cluster;
	u32 current_cluster = start_cluster;

	u8 *fat_sector_buffer = (u8*)kmalloc(512);
	if (!fat_sector_buffer) return 0;

	for (u32 i = 0; i < cluster_skip; ++i)
	{
		//compute which sector of the FAT map contains entry for current cluster
		u32 fat_sector = partition_offset + fat_start_sector + ((current_cluster * 4) / 512);
		u32 fat_offset = (current_cluster * 4) % 512;

		ata_read_sector(fat_sector, fat_sector_buffer);
		current_cluster = *(u32*)&fat_sector_buffer[fat_offset] & 0x0FFFFFFF;

		if (current_cluster >= 0x0FFFFFF8)
		{
			kfree(fat_sector_buffer);
			return 0; //unexpected early EOF(End Of File)
		}
	}

	//read data into the target buffer
	u32 bytes_read = 0;
	u32 cluster_offset = offset % bytes_per_cluster;
	u8* cluster_buffer = (u8*)kmalloc(bytes_per_cluster);
	if (!cluster_buffer)
	{
		kfree(fat_sector_buffer);
		return 0;
	}

	while (bytes_read < size)
	{
		//map phyiscal storage sectors matching this data cluster
		u32 start_sector = fat32_cluster_to_sector(current_cluster);

		//read the entire cluster into a temporary struct
		for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; s++)
		{
			ata_read_sector(start_sector + s, cluster_buffer + (s * 512));
		}

		//how much data is gonna be copied from this cluster
		u32 chunk_size = bytes_per_cluster - cluster_offset;
		if (chunk_size > (size - bytes_read)) chunk_size = size - bytes_read;
		//transfer raw data to the user space buffer
		for (u32 i = 0; i < chunk_size; ++i)
		{
			buffer[bytes_read + i] = cluster_buffer[cluster_offset + i];
		}

		bytes_read += chunk_size;
		cluster_offset = 0; //only the first clutser has original file offset
		u32 fat_sector = partition_offset + fat_start_sector + ((current_cluster * 4) / 512);
		u32 fat_offset = (current_cluster * 4) % 512;

		ata_read_sector(fat_sector, fat_sector_buffer);
		current_cluster = *(u32*)&fat_sector_buffer[fat_offset] & 0x0FFFFFFF;

		if (current_cluster >= 0x0FFFFFF8) break; //break out if EOF reached
	}

	kfree(cluster_buffer);
	kfree(fat_sector_buffer);
	return bytes_read;
}

u32 fat32_write(struct vfs_node* node, u32 offset, u32 size, u8* buffer)
{
	if (!node || mounted_bpb == NULL || size == 0) return 0;

	u32 bytes_per_clutser = mounted_bpb->sectors_per_cluster * 512;
	u32 current_cluster = node->inode;
    u32 initial_cluster = node->inode;

    //1. allocate initial cluster if file is brand new
    if (node->inode == 0)
    {
        u32 first_cluster = fat32_find_free_cluster();
        if (first_cluster == 0) return 0; //ze memory has been uh expended
        
        fat32_write_fat_entry(first_cluster, 0x0FFFFFFF); //Mark EOF
        node->inode = first_cluster;
        current_cluster = first_cluster; //Fix: keeping current_cluster in sync
        initial_cluster = first_cluster;
    }

    u32 cluster_skip = offset / bytes_per_clutser; //cluster_skip from offset

	u8* fat_sector_buffer = (u8*)kmalloc(512);
	if (!fat_sector_buffer) return 0;

    u32 last_cluster = current_cluster;

	//follow cluster chain to the offset location
	for (u32 i = 0; i < cluster_skip; i++)
	{
		u32 fat_sector = partition_offset + fat_start_sector + ((current_cluster * 4) / 512);
		u32 fat_offset = (current_cluster * 4) % 512;

		ata_read_sector(fat_sector, fat_sector_buffer);
		last_cluster = current_cluster;
		current_cluster = *(u32*)&fat_sector_buffer[fat_offset] & 0x0FFFFFFF;

		//allocate a new cluster chain link if writing way part current allocated clusters
		if (current_cluster >= 0x0FFFFFF8 || current_cluster == 0)
		{
			u32 free_cluster = fat32_find_free_cluster();
			if (free_cluster == 0)
			{
				kfree(fat_sector_buffer);
				return  0; //disk full!
			}
			fat32_write_fat_entry(last_cluster, free_cluster);
			fat32_write_fat_entry(free_cluster, 0x0FFFFFFF); //mark new EOF
			current_cluster =  free_cluster;
		}
	}

	u32 bytes_written = 0;
	u32 cluster_offset = offset % bytes_per_clutser;
	u8* cluster_buffer = (u8*)kmalloc(bytes_per_clutser);
	if (!cluster_buffer)
	{
			kfree(fat_sector_buffer);
			return 0;
	}

	//2. Main byte streaming loop
	while (bytes_written < size)
	{
		u32 start_sector = fat32_cluster_to_sector(current_cluster);

		//read the cluster first to preserve data boundaries we aren't changing
		for (u32 s = 0;  s < mounted_bpb->sectors_per_cluster; s++)
		{
			ata_read_sector(start_sector + s, cluster_buffer + (s * 512));
		}

		u32 chunk_size = bytes_per_clutser - cluster_offset;
		if (chunk_size > (size - bytes_written))
		{
			chunk_size = size - bytes_written;
		}

		//pverwrite the specific window inside ze cluster buffer
		for (u32 i = 0; i < chunk_size; i++)
		{
			cluster_buffer[cluster_offset + i] = buffer[bytes_written + i];
		}

		//commit full cluster data changes down to disk
		for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; s++)
		{
			ata_write_sector(start_sector + s, cluster_buffer + (s * 512));
		}

		bytes_written += chunk_size;
		cluster_offset  = 0; //subsequent loops write from cluster start line

		if (bytes_written < size)
		{
			u32 fat_sector = partition_offset + fat_start_sector + ((current_cluster * 4) / 512);
			u32 fat_offset = (current_cluster * 4) % 512;

			ata_read_sector(fat_sector, fat_sector_buffer);
			last_cluster = current_cluster;
			current_cluster = *(u32*)&fat_sector_buffer[fat_offset] & 0x0FFFFFFF;

			//allocate next chain node if file expansion is required
			if (current_cluster >= 0x0FFFFFF8 || current_cluster == 0)
			{
				u32 free_cluster = fat32_find_free_cluster();
				if (free_cluster == 0) break; //out of memory block bounds,  write what we can
				fat32_write_fat_entry(last_cluster, free_cluster);
				fat32_write_fat_entry(free_cluster, 0x0FFFFFFF);
				current_cluster = free_cluster;
			}
		}
	}

    u32 final_size = offset + bytes_written;
    if (final_size > node->size || initial_cluster != node->inode)
    {
        node->size = final_size;
        //flushes update starting cluster and size back to directory sectors
        fat32_sync_directory_metadata(node, current_dir_cluster, node->size, node->inode);
    }

	kfree(cluster_buffer);
	kfree(fat_sector_buffer);
	return bytes_written;
}

//converts a FAT32 Cluster index into a aw logical block address sector
u32 fat32_cluster_to_sector(u32 cluster)
{
	if (cluster < 2) return 0; //clusters 0 and 1 are invalid boundary tags
	return partition_offset + data_start_sector + ((cluster - 2) * mounted_bpb->sectors_per_cluster);
}

//custom helper that compares normal input string (eg. "bin")
// returns 0 on a perfect match...
int fat32_compare_name(const char* input_name, const u8* fat_name)
{
	char formatted_input[11];
	//pre-fill outr comparison buffer with standard FAT empty spaces
	for (int i = 0; i < 11; ++i) formatted_input[i] = ' ';

	int i = 0;
	//process main file/folder name postion (up to 8 bytes)
	while (input_name[i] != '\0' && input_name[i] != '.' && i < 8)
	{
		char c = input_name[i];
		if (c >= 'a' && c <= 'z') c -= 32; //convert to upper case...
		formatted_input[i] = c;
		i++;
	}

	if (input_name[i] == '.')
	{
		i++; //skipp the '.' character
		int ext_idx = 8;
		while (input_name[i] != '\0' && ext_idx < 11)
		{
			char c = input_name[i];
			if (c >= 'a' && c <= 'z') c -= 32;
			formatted_input[ext_idx] = c;
			i++;
			ext_idx++;
		}
	}

	//compare the raw 11 bytes completely
	for (int idx = 0;  idx < 11; idx++)
	{
		if (formatted_input[idx] != fat_name[idx])
		{
			return 1; //msimatch encountered
		}
	}
	return 0; //perfect match found!
}

struct vfs_node *fat32_finddir(struct vfs_node *dir_node, const char* name)
{
	//ensure we are working on a directory flag (0x02)
	if (!(dir_node->type & 0x02) || mounted_bpb == NULL) return NULL;

    u32 current_cluster = dir_node->inode;
    u32 bytes_per_sector = 512;
    u8 *buffer = (u8*)kmalloc(bytes_per_sector);
    if (!buffer) return NULL;

    u8 *fat_buffer = (u8*)kmalloc(bytes_per_sector);
    if (!fat_buffer) { kfree(buffer); return NULL; }

    //TRaverse the full cluster chain of the directory...
    while (current_cluster < 0x0FFFFFF8 && current_cluster != 0)
    {
        u32 start_sector = fat32_cluster_to_sector(current_cluster);

        //loop through EVERY sector inside the cluster....
        for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; s++)
        {
            ata_read_sector(start_sector + s, buffer);
            FAT32_DirEntry* entries = (FAT32_DirEntry*)buffer;

            for (int i = 0; i < 16; ++i)
            {
                if (entries[i].name[0] == 0x00) //End of directory stream...
                {
                    kfree(buffer);
                    kfree(fat_buffer);
                    return NULL;
                }
                if (entries[i].name[0] == 0xE5) continue; //deleted entry
                if (entries[i].attr == 0x0F) continue; //LFN entry
                if (entries[i].attr & 0x08) continue; //Volume Label
            
                if (fat32_compare_name(name, entries[i].name) == 0)
                {
                    struct vfs_node *child = (struct vfs_node*)kmalloc(sizeof(struct vfs_node));
                    if (!child) { kfree(buffer); kfree(fat_buffer); return NULL; }

                    //construct name and attributes
                    int c;
                    for (c = 0; c < 8 && entries[i].name[c] != ' '; c++)
                    {
                        child->name[c] = entries[i].name[c];
                    }
                    if (!(entries[i].attr & 0x10) && entries[i].name[8] != ' ')
                    {
                        child->name[c++] = '.';
                        for (int e = 8; e < 11 && entries[i].name[e] != ' '; e++)
                        {
                            child->name[c++] = entries[i].name[e];
                        }
                    }
                    child->name[c] = '\0';

                    child->size = entries[i].file_size;
                    child->inode = ((u32)entries[i].first_cluster_hi << 16) | entries[i].first_cluster_lo;
                
                    if (entries[i].attr & 0x10)
                    {
                        child->type = 0x02;
                        child->finddir = fat32_finddir; //its recursive?
                        child->read = NULL;
                        child->write = NULL;
                    } else {
                        child->type = 0x01;
                        child->finddir = NULL;
                        child->read = fat32_read;
                        child->write = fat32_write;
                    }

                    child->open = NULL;
                    child->close = NULL;

                    kfree(buffer);
                    kfree(fat_buffer);
                    return child;
                }
            }
        }

        //fetch next cluster from FAT table
        u32 fat_sector = partition_offset + fat_start_sector + ((current_cluster * 4) / 512);
        u32 fat_offset = (current_cluster * 4) % 512;
        ata_read_sector(fat_sector, fat_buffer);
        current_cluster = *(u32*)&fat_buffer[fat_offset] & 0x0FFFFFFF;
    }

    kfree(buffer);
    kfree(fat_buffer);
    return NULL;
}

int fat32_create_dir(u32 parent_cluster, const char* dirname)
{
	if (mounted_bpb == NULL) return 0;

	//claim ze free cluster
	u32 new_clus = fat32_find_free_cluster();
	if (new_clus == 0)
	{
		vga_puts("[ MKDIR ERROR ] - No free clusters available. \n");
		return 0;
	}

	//mark as EOF
	fat32_write_fat_entry(new_clus, 0x0FFFFFFF);

	//clear the allocated cluster memory
	u32 bytes_per_cluster = mounted_bpb->sectors_per_cluster * 512;
	u8* cluster_buffer = (u8*)kmalloc(bytes_per_cluster);
	if (!cluster_buffer) return 0;
	memset(cluster_buffer, 0, bytes_per_cluster);

	//structure the initial directory contents
	FAT32_DirEntry *entries = (FAT32_DirEntry*)cluster_buffer;

	// set up "." entry (current directory)
	memset(entries[0].name, ' ', 11);
	entries[0].name[0] = '.';
	entries[0].attr = 0x10; //attribute for directory
	entries[0].first_cluster_hi = (new_clus >> 16) & 0xFFFF;
	entries[0].first_cluster_lo = new_clus & 0xFFFF;
	entries[0].file_size = 0;

	//setup ".." entry (previous directory)
	memset(entries[1].name, ' ', 11);
	entries[1].name[0] = '.';
	entries[1].name[1] = '.';
	entries[1].attr = 0x10;

	u32 parent_target_val = (parent_cluster == mounted_bpb->root_cluster) ? 0 : parent_cluster;
	entries[1].first_cluster_hi = (parent_target_val >> 16) & 0xFFFF;
	entries[1].first_cluster_lo = parent_target_val & 0xFFFF;
	entries[1].file_size = 0;

	//commit these formatted entries onto the new sector
	u32 start_sector = fat32_cluster_to_sector(new_clus);
	for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; s++)
	{
		ata_write_sector(start_sector + s, cluster_buffer + (s * 512));
	}
	kfree(cluster_buffer);

	return fat32_add_entry(parent_cluster, dirname, 0x10, new_clus, 0);
}

//write new value to a specific slot in the FAT on the disk
void fat32_write_fat_entry(u32 cluster, u32 value)
{
	if (mounted_bpb == NULL) return;

	//each FAT entry is 4 bytes (32 bit)
	u32 fat_sector = partition_offset + fat_start_sector + ((cluster * 4) / 512);
	u32 fat_offset = (cluster * 4) % 512;

	u8 *fat_sector_buffer = (u8*)kmalloc(512);
	if (!fat_sector_buffer) return;

	//read the existing sector, modify, then write back...
	ata_read_sector(fat_sector, fat_sector_buffer);
	*(u32*)&fat_sector_buffer[fat_offset] = (value & 0x0FFFFFFF);//FAT32 uses 28 bit
	ata_write_sector(fat_sector, fat_sector_buffer);

	kfree(fat_sector_buffer);
}

//scans the FAT area for the first cluster than contains 0x00000000
u32 fat32_find_free_cluster(void)
{
	if (mounted_bpb == NULL) return 0;

	u8* fat_sector_buffer = (u8*)kmalloc(512);
	if (!fat_sector_buffer) return 0;

	//calculate how many total clusters are available on the drive
	u32 total_data_sectors = mounted_bpb->total_sectors_32 - data_start_sector;
	u32 total_clusters = total_data_sectors / mounted_bpb->sectors_per_cluster;

	//start scanning from cluster 2
	for (u32 cluster = 2; cluster < total_clusters + 2; cluster++)
	{
		u32 fat_sector = partition_offset + fat_start_sector + ((cluster * 4) / 512);
		u32 fat_offset = (cluster * 4) % 512;

		if (fat_offset == 0 || cluster == 2)
		{
			ata_read_sector(fat_sector, fat_sector_buffer);
		}

		u32 entry_val = *(u32*)&fat_sector_buffer[fat_offset] & 0x0FFFFFFF;
		if (entry_val == 0)
		{
			kfree(fat_sector_buffer);
			return cluster; //bingo! found a free slot!
		}
	}

	kfree(fat_sector_buffer);
	return 0; //DISK full!
}

//helper to pad/format the filename to the standard 8.3 FAT format
// example "test.txt" becomes "TEST  TXT"
void format_fat_name(const char* src, u8* dest)
{
	#define TO_UPPER(c) (((c) >= 'a' && (c) <= 'z') ? ((c) - 32) : (c))
	memset(dest, ' ', 11);
	int i = 0, j = 0;
	while (src[i] != '\0' && src[i] != '.' && j < 8)
	{
		dest[j++] = TO_UPPER(src[i]);
		i++;
	}

	if (src[i] == '.')
	{
		i++; //skip the '.'
		j = 8;
		while (src[i] && j < 11)
		{
			dest[j++] = TO_UPPER(src[i]);
			i++;
		}
	}
	#undef TO_UPPER
}

int fat32_add_entry(u32 dir_cluster, const char* filename, u8 attrib, u32 starting_cluster, u32 file_size)
{
	u32 bytes_per_cluster = mounted_bpb->sectors_per_cluster * 512;
	u8* buffer = (u8*)kmalloc(bytes_per_cluster);

	u32 base_sector = fat32_cluster_to_sector(dir_cluster);
	for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; s++)
	{
		ata_read_sector(base_sector + s, buffer + (s * 512));
	}

	FAT32_DirEntry *entries = (FAT32_DirEntry*)buffer;
	u32 max_entries = bytes_per_cluster / 32;
	int target_slot = -1;

	for (u32 i = 0; i < max_entries; ++i)
	{
		//found an empty or deleted slot...
		if (entries[i].name[0] == 0x00 || entries[i].name[0] == 0xE5)
		{
			target_slot = i;
			break;
		}
	}

	if (target_slot == -1)
	{
		kfree(buffer);
		return -1; //the directory is full if no free bytes are found
	}

	//populate the new directory entry...
	FAT32_DirEntry *new_entry = &entries[target_slot];
	format_fat_name(filename, new_entry->name);
	new_entry->attr = attrib;
	new_entry->first_cluster_lo = starting_cluster & 0xFFFF;
	new_entry->first_cluster_hi = (starting_cluster >> 16) & 0xFFFF;
	new_entry->file_size = file_size;
	//clear timestamps / creation dates for simplicity right now
	new_entry->nt_res = 0;
	new_entry->crt_time_ten = 0;

	//writ the updated cluster back to the disk
	for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; s++)
	{
		ata_write_sector(base_sector + s, buffer + (s * 512));
	}

	kfree(buffer);
	return 0; //success
}

void fat32_sync_directory_metadata(vfs_node_t *file_node, u32 parent_dir_cluster, u32 newsize, u32 first_cluster)
{
    u8 *sector_buffer = (u8*)kmalloc(512);
    if (!sector_buffer) return;

    u32 dir_sector = fat32_cluster_to_sector(parent_dir_cluster);
    FAT32_DirEntry *entries = (FAT32_DirEntry*)sector_buffer;

    //standard search loops acros the directory sectors
    for (u32 s = 0; s < mounted_bpb->sectors_per_cluster; ++s)
    {
        ata_read_sector(dir_sector + s, sector_buffer);

        for (int i = 0; i < 16; ++i)
        {
            //match based on the inode / starting cluster tag
            u32 entry_cluster = ((u32)entries[i].first_cluster_hi << 16) | entries[i].first_cluster_lo;
            if (entry_cluster == file_node->inode)
            {
                //update file size & starting cluster...
                entries[i].file_size = newsize;
                entries[i].first_cluster_hi = (u16)(first_cluster >> 16);
                entries[i].first_cluster_lo = (u16)(first_cluster & 0xFFFF);

                //commit back to physical disk sector
                ata_write_sector(dir_sector + s, sector_buffer);
                kfree(sector_buffer);
                return;
            }
        }
    }
    kfree(sector_buffer);
}

void cmd_touch(const char *filename)
{
	if (mounted_bpb == NULL)
	{
		vga_puts("[ ERROR ] - No mounted disk/drive. Cannot create file. \n");
		return;
	}
	//assume we track current_dir_cluster dynamically in the shell
	if (fat32_add_entry(current_dir_cluster, filename, 0x00, 0, 0) == 0)
	{
		vga_puts("[ SUCCESS ] - ");
		vga_puts(filename);
		vga_puts(" created successfully. \n");
	} else {
		vga_puts("[ ERROR ] - Could not create file. \n");
	}
}

//command: ls
void cmd_ls(u32 target_cluster)
{
	if (mounted_bpb == NULL)
	{
		vga_puts(" bin/"); //fallback to mock if hardware not mounted
		return;
	}

	u32 sector = fat32_cluster_to_sector(target_cluster);
	u8* buffer = (u8*)kmalloc(512);
	if (!buffer) return;

	ata_read_sector(sector, buffer);
	FAT32_DirEntry *entries = (FAT32_DirEntry*)buffer;

	//loop through 16 available 32-byte directory entry records in this 512 byte sector
	for (int i = 0; i < 16; ++i)
	{
		if (entries[i].name[0] == 0x00) break; //EOD(End Of Directory) stream mark
		if (entries[i].name[0] == 0xE5) continue; //deleted entry skip
		if (entries[i].attr == 0x0F) continue; //long file name helper metadeata skip
		if (entries[i].attr & 0x08) continue; //this skipes NO-NAME labels
		vga_puts(" ");
		//print main name(8 chars max)
		for (int c = 0; c < 8; c++)
		{
			if (entries[i].name[c] != ' ') vga_put_c(entries[i].name[c]);
		}

		//if it is a directory attribute (0x10 flag)
		if (entries[i].attr & 0x10)
		{
			vga_puts("/");
		} else { //it's a file and append its dot extension
			vga_puts(".");
			for (int c = 8; c < 11; c++)
			{
				if (entries[i].name[c] != ' ') vga_put_c(entries[i].name[c]);
			}
			vga_puts("   (");
			vga_put_num(entries[i].file_size);
			vga_puts(" bytes)");
		}
		vga_puts("\n");
	}
	kfree(buffer);
}

//Command: pwd
void cmd_pwd(void)
{
	vga_puts(current_working_dir);
	vga_puts("\n");
}

//Command: cd <folder>
void cmd_cd(const char* target_folder)
{
    if (mounted_bpb == NULL)
    {
        vga_puts("[ ERROR ] - No physical hardware mounted to support directory switching.\n");
        return;
    }

    // Edge case: Handle going back to root directory shortcut "cd /"
    if (strcmp(target_folder, "/") == 0)
    {
        current_dir_cluster = mounted_bpb->root_cluster;
        current_working_dir[0] = '/';
        current_working_dir[1] = '\0';
        return;
    }

    // Edge case: Handle going back to previous directory "cd .."
        if (strcmp(target_folder, "..") == 0)
        {
            if (strcmp(current_working_dir, "/") == 0) return; // Already at root

            u32 sector = fat32_cluster_to_sector(current_dir_cluster);
            u8 *buffer = (u8*)kmalloc(512);
            if (!buffer) return;

            ata_read_sector(sector, buffer);
            FAT32_DirEntry *entries = (FAT32_DirEntry*)buffer;
            int found = 0;

            for (int i = 0; i < 16; i++)
            {
                // FAT32 physically stores '..' starting with two dots
                if (entries[i].name[0] == '.' && entries[i].name[1] == '.')
                {
                    current_dir_cluster = ((u32)entries[i].first_cluster_hi << 16) | entries[i].first_cluster_lo;

                    // FAT32 Specification: A cluster value of 0 in the ".." entry points to the root directory
                    if (current_dir_cluster == 0) {
                        current_dir_cluster = mounted_bpb->root_cluster;
                    }
                    found = 1;
                    break;
                }
            }
            kfree(buffer);

            if (found)
            {
                // Rewind the current_working_dir string
                int len = 0;
                while (current_working_dir[len] != '\0') len++;

                // Step back from the trailing slash
                if (len > 1 && current_working_dir[len-1] == '/') {
                    len--;
                }

                // Delete characters until we hit the previous slash
                while (len > 0 && current_working_dir[len-1] != '/') {
                    len--;
                }

                // Cap the string
                if (len == 0) {
                    current_working_dir[0] = '/';
                    current_working_dir[1] = '\0';
                } else {
                    current_working_dir[len] = '\0';
                }
            }
            return;
        }

    u32 sector = fat32_cluster_to_sector(current_dir_cluster);
    u8 *buffer = (u8*)kmalloc(512);
    if (!buffer) return;

    ata_read_sector(sector, buffer);
    FAT32_DirEntry *entries = (FAT32_DirEntry*)buffer;
    int found = 0;

    for (int i = 0; i < 16; i++)
    {
        if (entries[i].name[0] == 0x00) break;
        if (entries[i].name[0] == 0xE5) continue;

        //Fix: skip the volume labels too...
        if (entries[i].attr == 0x0F) continue;
        if (entries[i].attr & 0x08) continue;

        // Check if the item is a valid directory
        if (entries[i].attr & 0x10)
        {
            // Use our newly constructed parser to see if the directory names align!
            if (fat32_compare_name(target_folder, entries[i].name) == 0)
            {
                // Pull the 32-bit destination cluster address from high and low entry word values
                current_dir_cluster = ((u32)entries[i].first_cluster_hi << 16) | entries[i].first_cluster_lo;

                // Concatenate the new folder name onto our human-readable path string
                int len = 0;
                while (current_working_dir[len] != '\0') len++;

                int t_idx = 0;
                while (target_folder[t_idx] != '\0' && len < 250)
                {
                    current_working_dir[len++] = target_folder[t_idx++];
                }
                current_working_dir[len++] = '/';
                current_working_dir[len] = '\0';

                found = 1;
                break;
            }
        }
    }

    if (!found)
    {
        vga_puts("/bin/ursh: cd: no such file or directory: ");
        vga_puts(target_folder);
        vga_puts("\n");
    }

    kfree(buffer);
}

#define _VGA_ADDRESS 0xB8000 //vga memory address
#define _VGA_COLS 80
#define _VGA_ROWS 25
#define _VGA_ATTR 0x0E //yellow on black

#define _PIC1_COMMAND 0x20
#define _PIC1_DATA    0x21 //master PIC
#define _PIC2_COMMAND 0xA0
#define _PIC2_DATA    0xA1	//slave PIC

#define _ICW1_INIT    0x11
#define _ICW4_8086    0x01

#define _VGA_BUFFER ((volatile u16*)_VGA_ADDRESS)
static long unsigned int cursor_pos = 0;

void pic_remap(void);
void outb(u16 port, u8 val);
void serial_puts(const char* str);
void serial_put_c(char c);
void mouse_wait(u8 type);
void mouse_write(u8 val);
void mouse_init(void);

// Sends a 16-bit word to a hardware port
void outw(u16 port, u16 val) {
    __asm__ volatile ("outw %0, %1" : : "a"(val), "Nd"(port));
}

u16 inw(u16 port)
{
	u16 ret;
	__asm__ volatile("inw %1, %0" : "=a"(ret) : "Nd"(port));
	return ret;
}

int strcmp(const char* s1, const char* s2)
{
	while (*s1 && (*s1 == *s2))
	{
		s1++;
		s2++;
	}
	return *(const unsigned char*)s1 - *(const unsigned char*)s2;
}

void memset(void *dest, u8 val, u32 len)
{
	u8* ptr = (u8*)dest;
	while (len--)
	{
		*ptr++ = val;
	}
}

void vga_scroll(void)
{
	u16 *vga = (u16*)_VGA_ADDRESS;

	//physically shift rows 1 to 24 up by one row
	for (int y = 0; y < _VGA_ROWS - 1; y++)
	{
		for (int x = 0; x < _VGA_COLS; x++)
		{
			vga[y * _VGA_COLS + x] = vga[(y + 1) * _VGA_COLS + x];
		}
	}

	//clear out the very bottom row (row 24) to make it empty space
	u16 blank_cell = (u16)' ' | ((u16)_VGA_ATTR << 8);
	for (int x = 0; x < _VGA_COLS; x++)
	{
		vga[(_VGA_ROWS - 1) * _VGA_COLS + x] = blank_cell;
	}
}

void vga_put_c(char c)
{
	//handle new-line character...
	if (c == '\n')
	{
		cursor_pos = (cursor_pos / _VGA_COLS + 1) * _VGA_COLS;
	} else if (c == '\b'){
		//handling backspace...
		if (cursor_pos > 0)
		{
			cursor_pos--;
			_VGA_BUFFER[cursor_pos] = (u16)32 | ((u16)_VGA_ATTR << 8);
		}
	} else {
		//print the char like that if it's not backspace or new-line...
		_VGA_BUFFER[cursor_pos] = (u16)c | ((u16)_VGA_ATTR << 8);
		cursor_pos++;
	}

	//automatic scroll check
	if (cursor_pos >= _VGA_COLS * _VGA_ROWS)
	{
		vga_scroll();
		//snap cursor bact to the very start of the very lat line
		cursor_pos = (_VGA_ROWS - 1) * _VGA_COLS;
	}

	// Keep the physical blinking cursor locked to our tracking pointer
	outb(0x3D4, 0x0F);
	outb(0x3D5, (u8)(cursor_pos & 0xFF));
	outb(0x3D4, 0x0E);
	outb(0x3D5, (u8)((cursor_pos >> 8) & 0xFF));
}

//prints text to vga buffer
void vga_puts(const char* str)
{
	while(*str)
	{
		vga_put_c(*str++);
	}
}

void vga_put_num(u32 num)
{
	if (num == 0)
	{
		vga_put_c('0');
		return;
	}
	char buf[12];
	int i = 10;
	buf[11] = '\0';
	while (num > 0 && i >= 0)
	{
		buf[i--] = (num % 10) + '0';
		num /= 10;
	}
	vga_puts(&buf[i + 1]);
}

//this method remaps the entries since long ago the PIC and Exceptions collide...
//...so this maps the PIC IRQs at different addresses from the CPU Exceptions
// Small delay for I/O operations
void io_wait(void) {
    outb(0x80, 0);
}

void pic_remap(void) {
    // Start initialization sequence
    outb(_PIC1_COMMAND, _ICW1_INIT); io_wait();
    outb(_PIC2_COMMAND, _ICW1_INIT); io_wait();

    // Set offsets (Master: 0x20, Slave: 0x28)
    outb(_PIC1_DATA, 0x20); io_wait();
    outb(_PIC2_DATA, 0x28); io_wait();

    // Tell Master there is a slave PIC at IRQ2
    outb(_PIC1_DATA, 4); io_wait();
    // Tell Slave its cascade identity
    outb(_PIC2_DATA, 2); io_wait();

    // Set mode to 8086/88
    outb(_PIC1_DATA, _ICW4_8086); io_wait();
    outb(_PIC2_DATA, _ICW4_8086); io_wait();

    // Mask all interrupts until ready
    outb(_PIC1_DATA, 0xFF); io_wait();
    outb(_PIC2_DATA, 0xFF); io_wait();
}

//outb bytes, sends data to ports/hardware(i guess)
void outb(u16 port, u8 val) {
    __asm__ volatile ("outb %0, %1" : : "a"(val), "Nd"(port));
}

//opposite or outb, reads...
u8 inb(u16 port)
{
	u8 ret;
	__asm__ volatile ("inb %1, %0" : "=a"(ret) : "Nd"(port));
	return ret;
}

//PIC End Of Interrupt, this tells the PIC when an ISR is over...
//...and it should tell CPU to continuw what is was doing "hlt" hehe
void pic_eoi(int irq)
{
	if (irq >= 8) outb(_PIC2_COMMAND, 0x20);
	outb(_PIC1_COMMAND, 0x20);
}

typedef struct {
    u16 offset_low;      // Low 16 bits of handler address
    u16 selector;        // Segment selector(normally 0x08 form our GDT remember?)
    u8 zero;             // Always 0
    u8 type_attr;        // 0x8E = interrupt gate
    u16 offset_high;     // High 16 bits of handler address
} __attribute__((packed)) IDT_Entry;

typedef struct {
    u16 size;            // Size of IDT - 1
    u32 address;         // Address of IDT array
} __attribute__((packed)) IDTR;

#define _IDT_ENTRIES 256
static IDT_Entry idt[_IDT_ENTRIES]; //create the 256 IDT entries

//printf hexadecimal text...
void vga_put_hex(u32 num)
{
    const char *hex = "0123456789ABCDEF";

    vga_puts("0x");

    // Print each hex digit
    for (int i = 7; i >= 0; i--)
    {
        u8 digit = (num >> (i * 4)) & 0xF;
        vga_put_c(hex[digit]);
    }
}

// Function to set one IDT entry
void idt_set_entry(int index, u32 handler_addr, u16 selector, u8 type_attr)
{
    idt[index].offset_low = handler_addr & 0xFFFF;           // Low 16 bits
    idt[index].offset_high = (handler_addr >> 16) & 0xFFFF;  // High 16 bits
    idt[index].selector = selector;
    idt[index].zero = 0;
    idt[index].type_attr = type_attr;
}

// Load IDT into CPU
void idt_load(void)
{
    static IDTR idtr; // Static ensures it stays in memory
    idtr.size = (sizeof(IDT_Entry) * _IDT_ENTRIES) - 1;
    idtr.address = (u32)&idt;

    __asm__ volatile("lidt %0" : : "m"(idtr));
}

//various handlers...
//because of __attribute__((interrupt)) we dont have to make an externel ISR stub
//and it auto returns iret not ret so the CPU knows its an interrupt
__attribute__((interrupt)) void divide_by_zero_handler(void *frame)
{
    vga_puts("\n=== INTERRUPT #0: DIVIDE BY ZERO ===\n");
    vga_puts("A program tried to divide by zero!\n");
    vga_puts("System halted.\n");

    while(1)
    {
        __asm__("hlt");
    }
}

__attribute__((interrupt)) void debug_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #1: DEBUG ===\n");
	vga_puts("Debug exception triggered (breakpoint/single-step).\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void nmi_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #2: NON-MASKABLE INTERRUPT ===\n");
	vga_puts("Hardware error detected!\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void breakpoint_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #3: BREAKPOINT ===\n");
	vga_puts("Breakpoint hit (int3 instruction).\n");
}

__attribute__((interrupt)) void overflow_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #4: OVERFLOW ===\n");
	vga_puts("Signed integer overflow detected!\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void bound_range_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #5: BOUND RANGE EXCEEDED ===\n");
	vga_puts("Array index out of bounds (BOUND instruction).\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void invalid_opcode_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #6: INVALID OPCODE ===\n");
	vga_puts("CPU executed an unknown instruction!\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void device_not_available_handler(void *frame)
{
	vga_puts("\n=== EXCEPTION #7: DEVICE NOT AVAILABLE ===\n");
	vga_puts("Floating point unit not enabled or missing.\n");
	while(1) __asm__("hlt");
}

// Double Fault has error code - different signature
__attribute__((interrupt)) void double_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #8: DOUBLE FAULT ===\n");
	vga_puts("Processor couldn't handle another exception!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void invalid_tss_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #10: INVALID TSS ===\n");
	vga_puts("Task state segment is invalid!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void segment_not_present_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #11: SEGMENT NOT PRESENT ===\n");
	vga_puts("Segment descriptor not present in memory!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void stack_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #12: STACK-SEGMENT FAULT ===\n");
	vga_puts("Stack segment violation!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void general_protection_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #13: GENERAL PROTECTION FAULT ===\n");
	vga_puts("Memory protection violation!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void floating_point_exception_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #16: FLOATING POINT EXCEPTION ===\n");
	vga_puts("Math Error in the FPU\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

// Page Fault has error code
__attribute__((interrupt)) void page_fault_handler(void *frame, u32 error_code)
{
	vga_puts("\n=== EXCEPTION #14: PAGE FAULT ===\n");
	vga_puts("Memory page not present or access violation!\n");
	vga_puts("Error code: ");
	vga_put_hex(error_code);
	vga_puts("\n");

	// Read faulting address from CR2 register
	u32 faulting_addr;
	__asm__("mov %%cr2, %0" : "=r"(faulting_addr));
	vga_puts("Faulting address: ");
	vga_put_hex(faulting_addr);
	vga_puts("\n");

	while(1) __asm__("hlt");
}

__attribute__((interrupt)) void alignment_check_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #17: ALIGNMENT CHECK ===\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

__attribute__((interrupt)) void machine_check_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #18: MACHINE CHECK ===\n");
	vga_puts("Fatal hardware error!\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

__attribute__((interrupt)) void simd_floating_point_exception_handler(void *frame, u32 error_code)
{
	vga_puts("\n===EXCEPTION #19: SIMD FLOATING-POINT EXCEPTION ===\n");
	vga_puts("Math Error in the SSE/AVX\n");
	vga_puts("Error Code: ");
	vga_put_hex(error_code);
	vga_puts("\n");
	while(1)
		__asm__("hlt");
}

#define _PIT_COMMAND 0x43
#define _PIT_CHANNEL0 0x40

// Configure PIT to fire at a specific frequency (Hz)
void pit_init(u32 frequency) {
    // 1193182 Hz is the internal PIT oscillator frequency
    u32 divisor = 1193182 / frequency;

    // Command byte: Channel 0, access lo/hi byte, square wave mode, 16-bit binary
    // 0x36 = 00110110b
    outb(_PIT_COMMAND, 0x36);

    // Send divisor split across low byte and high byte
    outb(_PIT_CHANNEL0, (u8)(divisor & 0xFF));
    outb(_PIT_CHANNEL0, (u8)((divisor >> 8) & 0xFF));
}

static u32 timer_ticks = 0; //timer ticks...

void sleep(u32 milliseconds)
{
	u32 target_ticks = timer_ticks + milliseconds;

	while (timer_ticks < target_ticks)
	{
		__asm__ volatile("hlt");
	}
}

__attribute__((interrupt)) void timer_handler(void *frame)
{
	timer_ticks++;
	pic_eoi(0);
	//we'll make use of this again when making a sleep() command...
}

//buffer for keyboard buffer (keyboard driver)
#define _BUFFER_SIZE 64

//array of characters for the buffer
volatile char key_buffer[_BUFFER_SIZE];
//keeps track of current buffer status
volatile int buffer_head = 0;
volatile int buffer_tail = 0;

// Add a character to the buffer
void buffer_push(char c) {
    int next_head = (buffer_head + 1) % _BUFFER_SIZE;

    //prevent ring buffer overwrite if queue is full
    if (next_head == buffer_tail)
    {
        return;     //drop key or handle overrun safely
    }

    key_buffer[buffer_head] = c;
    buffer_head = next_head;
}

// Remove and return a character from the buffer
char buffer_pop(void) {
    //atomically check buffer bounds
    if (buffer_head == buffer_tail) return 0;

    char c = key_buffer[buffer_tail];
    buffer_tail = (buffer_tail + 1) % _BUFFER_SIZE;
    return c;
}

//special case keys for the keyboard interrpt and drivers
int shift_pressed = 0;
int caps_lock = 0;
int ctrl_key = 0;

// The index is the scan code. 0 means "no character".
//current characters the CPU can read from the keyboard
const char kdb_map[] = {
    0, 27, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',
    '\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n',
    0, 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', 0, '\\',
    'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 0, '*', 0, ' '
};

__attribute__((interrupt)) void keyboard_handler(void *frame)
{
	u8 scancode = inb(0x60); //read from the keyboard PIC ports

	//detect if it is a break code... (key release)
	if (scancode & 0x80)
	{
		u8 release_code = scancode - 0x80;
		if (release_code == 0x2A || release_code == 0x36) //left & right SHIFT
		{
			shift_pressed = 0;
		}
	}

	//logic if it's not a break code...
	else {
		if (scancode == 0x2A || scancode == 0x36) //left & right SHIFT
		{
			shift_pressed = 1;
		} else if (scancode == 0x3A){
			//caps-lock...
			caps_lock = !caps_lock;
		} else if (scancode == 0x0E){
			//backspace '\b'
			buffer_push('\b');
		} else {
			char c = kdb_map[scancode];
			if (c != 0)
			{
				//if shift is pressed...
				if (shift_pressed && c >= 'a' && c <= 'z')
				{
					//convert to upper-case...
					c -= 32;
				} else if (caps_lock && c >= 'a' && c <='z'){
					//if caps_lock is pressed...
					c -= 32;
				}

				buffer_push(c);
			}
		}
	}
	pic_eoi(1);
}

//the COM1 port handler...
__attribute__((interrupt)) void com1_handler(void *frame)
{
	vga_puts("COM1 Activity!\n");
	pic_eoi(4);
}

//MOUSE INIT, waking up the mouse...
// mouse wait method, to wait for input to be data to be ready or...
// ...input to be empty
void mouse_wait(u8 type)
{
	u32 timeout = 100000;
	if (type == 0) //wait for ready data to be read...
	{
		while (--timeout && !(inb(0x64) & 1));
	} else { //wait for buffer to be empty to write...
		while (--timeout && (inb(0x64) & 2));
	}
}

//writes to the mouse, [data]
void mouse_write(u8 val)
{
	mouse_wait(1); //wait for input to be empty
	outb(0x64, 0xD4); //send to the Mouse PIC port that we wanna write
	mouse_wait(1);
	outb(0x60, val); //send the actual data
}

//initializes the mouse
void mouse_init(void)
{
    u8 status;

    mouse_wait(1);
    outb(0x64, 0xA8); // Enable mouse port

    mouse_wait(1);
    outb(0x64, 0x20); // Read Command Byte
    mouse_wait(0);
    status = inb(0x60);
    status |= 3;      // SET BOTH BIT 0 (Keyboard) AND BIT 1 (Mouse)

    mouse_wait(1);
    outb(0x64, 0x60); // Write Command Byte
    mouse_wait(1);
    outb(0x60, status);

    mouse_write(0xF6); // Set defaults
    mouse_write(0xF4); // Enable data reporting
}

//mouse driver init...
u8 mouse_packet[3];
u8 mouse_cycle = 0; //tracks which byte from 0,1,2 we are on!

__attribute__((interrupt)) void mouse_handler(void *frame)
{
	u8 status = inb(0x64); //read status register to ensure data is ready

	if (status & 0x01) //if there's data to read...
	{
		u8 data = inb(0x60);

		switch (mouse_cycle)
		{
			case 0: //byte 1: status
				mouse_packet[0] = data;
				mouse_cycle = 1;
				break;
			case 1: //byte 2: X-Movement
				mouse_packet[1] = data;
				mouse_cycle = 2;
				break;
			case 2: //byte 3: Y-Movement
				mouse_packet[2] = data;
				mouse_cycle = 0; //Reset for the next packet
				//Here we will process the full packet
				serial_puts("mouse moved!");
				break;
		}
	}
	pic_eoi(12);
}

// Generic interrupt handler
// This handles unexpected interrupts that haven't been mapped yet...
__attribute__((interrupt)) void default_interrupt_handler(void *frame) {
    vga_puts("\n=== UNEXPECTED INTERRUPT ===\n");
    vga_puts("An unexpected interrupt occurred! System halted.\n");
    while(1) {
        __asm__("hlt");
    }
}

//initializees the IDT
void idt_init(void)
{
    __asm__("cli"); //clear interrupts

    vga_puts("Initializing IDT...\n");

    // Clear all IDT entries first and set them to default handler
    for (int i = 0; i < _IDT_ENTRIES; i++)
    {
        // Use 0x8E for interrupt gate, Present bit set, ring 0, interrupt gate
        idt_set_entry(i, (u32)default_interrupt_handler, 0x08, 0x8E);
    }

    // Set up specific handlers (will overwrite default for these)
    idt_set_entry(0, (u32)divide_by_zero_handler, 0x08, 0x8E);
    idt_set_entry(1, (u32)debug_handler, 0x08, 0x8E);
    idt_set_entry(2, (u32)nmi_handler, 0x08, 0x8E);
    idt_set_entry(3, (u32)breakpoint_handler, 0x08, 0x8E);
    idt_set_entry(4, (u32)overflow_handler, 0x08, 0x8E);
    idt_set_entry(5, (u32)bound_range_handler, 0x08, 0x8E);
    idt_set_entry(6, (u32)invalid_opcode_handler, 0x08, 0x8E);
    idt_set_entry(7, (u32)device_not_available_handler, 0x08, 0x8E);
    idt_set_entry(8, (u32)double_fault_handler, 0x08, 0x8E);
    idt_set_entry(10, (u32)invalid_tss_handler, 0x08, 0x8E);
    idt_set_entry(11, (u32)segment_not_present_handler, 0x08, 0x8E);
    idt_set_entry(12, (u32)stack_fault_handler, 0x08, 0x8E);
    idt_set_entry(13, (u32)general_protection_fault_handler, 0x08, 0x8E);
    idt_set_entry(14, (u32)page_fault_handler, 0x08, 0x8E);
    idt_set_entry(16, (u32)floating_point_exception_handler, 0x08, 0x8E);
    idt_set_entry(17, (u32)alignment_check_handler, 0x08, 0x8E);
    idt_set_entry(18, (u32)machine_check_handler, 0x08, 0x8E);
    idt_set_entry(19, (u32)simd_floating_point_exception_handler, 0x08, 0x8E);

    // IRQ handlers (PIC mapped IRQs)
    idt_set_entry(0x20, (u32)timer_handler, 0x08, 0x8E); // IRQ0 - Timer
    idt_set_entry(0x21, (u32)keyboard_handler, 0x08, 0x8E); // IRQ1 - Keyboard
    idt_set_entry(0x24, (u32)com1_handler, 0x08, 0x8E); // IRQ4 - COM1
    idt_set_entry(0x2C, (u32)mouse_handler, 0x08, 0x8E); // IRQ12 - Mouse

    // Load IDT into CPU
    idt_load();
    //__asm__("sti"); //start interrupts
}

//... (rest of the file)

#define _COM1 0x3f8

//starts the serial_driver and it listens...
//..like a radio
void serial_init(void)
{
    // 1. Disable all interrupts (we are doing polling for now)
    outb(_COM1 + 1, 0x00);
    // 2. Enable DLAB (set divisor mode)
    outb(_COM1 + 3, 0x80);
    // 3. Set divisor to 3 (38400 baud)
    outb(_COM1 + 0, 0x03);
    outb(_COM1 + 1, 0x00);
    // 4. 8 bits, no parity, one stop bit
    outb(_COM1 + 3, 0x03);
    // 5. Enable FIFO, clear them, with 14-byte threshold
    outb(_COM1 + 2, 0xC7);
    // 6. IRQs enabled, RTS/DSR set
    outb(_COM1 + 4, 0x0B);
}

//to check if there is 'noise', if there is we can't print
//and we wait for the noise to settle then
int is_transmit_empty(void)
{
	return inb(_COM1 + 5) & 0x20;
}

//prints a character to 0x3f8
void serial_put_c(char c)
{
	while (is_transmit_empty() == 0);
	outb(_COM1, c);
}

//prints text to 0x3f8
void serial_puts(const char* str)
{
	while (*str)
	{
		serial_put_c(*str++);
	}
}

void qemu_shutdown(void) {
    // QEMU newer versions / Bochs ACPI shutdown
    outw(0x604, 0x2000);
    // QEMU older versions (VirtualBox / PCem often support this port too)
    outw(0xB004, 0x2000);
}

// ATA/IDE Drive Controller Communication
// Returns 1 if a drive is successfully identified, 0 if empty/errored
int ata_identify_slave(void)
{
	// 1. Select primary slave drive (0xB0 maps to slave in primary channel)
	outb(0x1F6, 0xB0);

	// 2. Zero out sector count and LBA Parameters
	outb(0x1F2, 0x00);
	outb(0x1F3, 0x00);
	outb(0x1F4, 0x00);
	outb(0x1F5, 0x00);

	// 3. Send identify command (0xEC)
	outb(0x1F7, 0xEC);

	// 4. Poll status register
	u8 status = inb(0x1F7);
	if (status == 0)
	{
		return 0; // Drive doesn't exist
	}

	// 5. Wait for BSY bit 7 to clear and DRQ(Data ReQuest) bit 3 to set
	while ((status & 0x80) && !(status & 0x08))
	{
		status = inb(0x1F7);
	}

	if (status & 0x01)
	{
		return 0; // Drive flagged an error status
	}

	// 6. Pull the 512 byte metadata buffer via inw()
	u16 info[256];
	for (int i = 0; i < 256; ++i)
	{
		info[i] = inw(0x1F0);
	}

	vga_puts("[ HARDWARE ] - Storage device detected: ");

	// Drive model description string lives across words 27 to 46
	for (int i = 27; i <= 46; i++)
	{
		char high = (char)(info[i] >> 8);  // Upper byte
		char low  = (char)(info[i] & 0xFF); // Lower byte

		// ATA text standard streams characters byte-swapped
		if (high != ' ') vga_put_c(high);
		if (low != ' ')  vga_put_c(low);
	}

	// Extract total 28-bit LBA sectors out of words 60 and 61
	u32 total_sectors = ((u32)info[61] << 16) | info[60];
	vga_puts(" (");
	vga_put_num((total_sectors * 512) / (1024 * 1024));
	vga_puts(" MB)\n");

	return 1; // Drive successfully loaded!
}

#define _ATA_PRIMARY_DATA 0x1F0
#define _ATA_PRIMARY_ERR 0x1F1
#define _ATA_PRIMARY_SECCOUNT 0x1F2
#define _ATA_PRIMARY_LBA_LOW 0x1F3
#define _ATA_PRIMARY_LBA_MID 0x1F4
#define _ATA_PRIMARY_LBA_HIGH 0x1F5
#define _ATA_PRIMARY_DRIVE 0x1F6
#define _ATA_PRIMARY_STATUS 0x1F7
#define _ATA_PRIMARY_COMMAND 0x1F7

#define _ATA_CMD_WRITE_PIO 0x30
#define _ATA_STATUS_BSY 0x80
#define _ATA_STATUS_DRQ 0x08

static void ata_io_delay(void)
{
    //create a 400ns delay so that the CPU will have enought time to read from the status register
    inb(0x3F6); //reading byte from these port cause a 100ns delay so...we read 4-times...
    inb(0x3F6);
    inb(0x3F6);
    inb(0x3F6);
}

//note: LBA(Logical Block Address)
void ata_read_sector(u32 lba, u8* buffer)
{
	//send the bits 24-27 of lba along with drive identifier
	outb(0x1F6, 0xF0 | ((lba >> 24) & 0x0F));
	outb(0x1F2, 1); //1 sector at a time...
	//send rem lba bytes sequentially across ports
	outb(0x1F3, (u8)lba); //bits 0-7
	outb(0x1F4, (u8)(lba >> 8)); //bits 8-15
	outb(0x1F5, (u8)(lba >> 16)); //bits 16-23

	//fire the reaad sectors command register byte
	outb(0x1F7, 0x20); //after this read command we delay here!

    ata_io_delay(); //NOT THAT CRUCIAL, BUT NEEDED!

	//poll the status register until the drive is ready with data
	u8 status = inb(0x1F7);

	//wait while drive is BSY (bit 7)
	while (status & 0x80)
	{
		status = inb(0x1F7);
	}

	//check if err bit (bit 0)
	if (status & 0x01)
	{
		vga_puts("[ ATA ERROR ] - Drive rejected the read command. \n");
		vga_puts("[ ATA ERROR ] - Read failed! \n");
        return;
	}

	while (!(status & 0x08))
	{
		status = inb(0x1F7);
	}

	//pull 256 word (512 bytes) out of the data channel port
	u16 *ptr = (u16*)buffer;
	for (int i = 0; i < 256; ++i)
	{
		ptr[i] = inw(0x1F0);
	}
}

void ata_write_sector(u32 lba, u8* buffer)
{
	//wait for drive to not be busy
	while(inb(_ATA_PRIMARY_STATUS) & _ATA_STATUS_BSY);

	//select the drive (Master) and pass the highest 4 bits of the LBA
	outb(_ATA_PRIMARY_DRIVE, 0xF0 | ((lba >> 24) & 0x0F));

	//send the sector count (1 sector at a time)
	outb(_ATA_PRIMARY_SECCOUNT, 1);

	//send the rest of ze LBA bytes
	outb(_ATA_PRIMARY_LBA_LOW, (u8)lba);
	outb(_ATA_PRIMARY_LBA_MID, (u8)(lba >> 8));
	outb(_ATA_PRIMARY_LBA_HIGH, (u8)(lba >> 16));

	//issue the write PIO command
	outb(_ATA_PRIMARY_COMMAND, _ATA_CMD_WRITE_PIO);

	while (!(inb(_ATA_PRIMARY_STATUS) & _ATA_STATUS_DRQ));

	//write 256 words (512 bytes) to the data port
	u16 *ptr = (u16*)buffer;
	for (int i = 0; i < 256; ++i)
	{
		outw(_ATA_PRIMARY_DATA, ptr[i]);
	}

	//flush the cache
	outb(_ATA_PRIMARY_COMMAND, 0xE7);
	while (inb(_ATA_PRIMARY_STATUS) & _ATA_STATUS_BSY);
}

#define _SHELL_BUFFER_SIZE  256
char shell_buffer[_SHELL_BUFFER_SIZE];
u32 shell_index = 0;

void cmd_fetch(void)
{
    // 1. Compute Uptime from PIT timer ticks (1000 Hz)
    // Access global tick counter
    u32 total_seconds = timer_ticks / 1000;
    u32 minutes = total_seconds / 60;
    u32 seconds = total_seconds % 60;

    // 2. Query Physical Memory Manager (PMM) stats
    u32 actual_free_blocks = 0;
    for (u32 i = 0; i < max_blocks; i++) {
        if (!bitmap_test(i)) {
            actual_free_blocks++;
        }
    }
    u32 free_mb = actual_free_blocks / 256;  // 256 blocks * 4KB = 1MB
    u32 total_mb = max_blocks / 256;
    u32 used_mb = (total_mb > free_mb) ? (total_mb - free_mb) : 0;

    vga_puts("\n");
    vga_puts(" _   _ ____   ___  ____   root@uros\n");
    vga_puts("| | | |  _ \\ / _ \\/ ___|  --------------\n");
    vga_puts("| | | | |_) | | | \\___ \\  OS: UROS v1.0.0 (x86_32 Monolithic)\n");
    vga_puts("| |_| |  _ <| |_| |___) | Kernel: Custom C/x86 ASM Kernel\n");
    vga_puts(" \\___/|_| \\_\\___/|____/   Uptime: ");
    vga_put_num(minutes);
    vga_puts("m ");
    vga_put_num(seconds);
    vga_puts("s\n");

    vga_puts("                          Shell: ursh (UR SHell)\n");

    vga_puts("                          Display: VGA Text Mode (80x25)\n");

    vga_puts("                          RAM: ");
    vga_put_num(used_mb);
    vga_puts(" MB / ");
    vga_put_num(total_mb);
    vga_puts(" MB\n");

    vga_puts("                          Storage / VFS {urfs}: ");
    if (mounted_bpb != NULL) {
        vga_puts("FAT32 Volume (Hardware)\n");
    } else {
        vga_puts("RAM-Backed Mock FS\n");
    }

    vga_puts("                          PWD: ");
    vga_puts(current_working_dir);
    vga_puts("\n\n");
}

//text buffer, my own custom nano
#define _EDIT_ROWS 24
#define _EDIT_COLS 80
#define _EDIT_BUF_SIZE (_EDIT_ROWS * _EDIT_COLS)
#define _STATUS_ROW 24

//Render bootom status bar with reverse-video attribute (Black on Light Gray)
static void editor_draw_status(const char *filename, u32 cursor_x, u32 cursor_y)
{
    volatile u16 *vga = (volatile u16 *)_VGA_ADDRESS;
    u16 status_attr = (u16)0x70 << 8;

    //clear status bar line
    for (int x = 0; x < _EDIT_COLS; x++)
    {
        vga[_STATUS_ROW * _EDIT_COLS + x] = (u16)' ' | status_attr;
    }

    //print Header & Filename
    const char *hdr = "[ UROS buffer ] File: ";
    int pos = 0;
    while (*hdr && pos < _EDIT_COLS)
    {
        vga[_STATUS_ROW * _EDIT_COLS + pos] = (u16)(*hdr++) | status_attr;
        pos++;
    }
    while (*filename && pos < 45)
    {
        vga[_STATUS_ROW * _EDIT_COLS] = (u16)(*filename++) | status_attr;
        pos++;
    }

    //display cursor coordinates and exit command
    const char *ctrl_msg = "ESC: Save and Exit";
    int msg_idx = 0;
    for (int x = 60; x < _EDIT_COLS && ctrl_msg[msg_idx]; x++)
    {
        vga[_STATUS_ROW * _EDIT_COLS + x] = (u16)ctrl_msg[msg_idx++] |status_attr;
    }

    //lock VGA hardware blinking cursor to edit postion
    u32 hw_pos = cursor_y * _EDIT_COLS + cursor_x;
    outb(0x3D4, 0x0F);
    outb(0x3D5, (u8)(hw_pos & 0xFF));
    outb(0x3D4, 0x0E);
    outb(0x3D5, (u8)((hw_pos >> 8) & 0xFF));
}

void cmd_buffer(const char *filename) {
    if (!filename || filename[0] == '\0') {
        vga_puts("[ URBUFFER ERROR ] Usage: buffer <filename>\n");
        return;
    }

    // Allocate editor working buffer on kernel heap
    char *text_buf = (char *)kmalloc(_EDIT_BUF_SIZE);
    if (!text_buf) {
        vga_puts("[ URBUFFER ERROR ] Out of memory. Heap allocation failed.\n");
        return;
    }
    memset(text_buf, ' ', _EDIT_BUF_SIZE);

    // Clear editing space on screen (Rows 0-23)
    volatile u16 *vga = (volatile u16 *)_VGA_ADDRESS;
    for (int i = 0; i < _EDIT_COLS * _EDIT_ROWS; i++) {
        vga[i] = (u16)' ' | ((u16)_VGA_ATTR << 8);
    }

    u32 cur_x = 0;
    u32 cur_y = 0;

    // Load existing file data if available via FAT32 / VFS
    if (mounted_bpb != NULL) {
        vfs_node_t *existing_file = fat32_finddir(vfs_root, filename);
        if (existing_file) {
            u32 read_bytes = fat32_read(existing_file, 0, _EDIT_BUF_SIZE, (u8 *)text_buf);
            
            // Render loaded content into VGA memory
            u32 r_x = 0, r_y = 0;
            for (u32 i = 0; i < read_bytes; i++) {
                char ch = text_buf[i];
                if (ch == '\n') {
                    r_y++;
                    r_x = 0;
                } else {
                    vga[r_y * _EDIT_COLS + r_x] = (u16)ch | ((u16)_VGA_ATTR << 8);
                    r_x++;
                    if (r_x >= _EDIT_COLS) { r_x = 0; r_y++; }
                }
                if (r_y >= _EDIT_ROWS) break;
            }
            kfree(existing_file);
        }
    }

    editor_draw_status(filename, cur_x, cur_y);

    int editing = 1;
    while (editing) {
        char c = buffer_pop();

        if (c == 0) {
            __asm__ volatile("hlt"); // Put CPU into low-power sleep while waiting for IRQ1
            continue;
        }

        // ESC Key (ASCII 27): Trigger Save & Exit pipeline
        if (c == 27) {
            editing = 0;
            break;
        }
        
        // Handle Backspace
        else if (c == '\b') {
            if (cur_x > 0) {
                cur_x--;
            } else if (cur_y > 0) {
                cur_y--;
                cur_x = _EDIT_COLS - 1;
            }
            text_buf[cur_y * _EDIT_COLS + cur_x] = ' ';
            vga[cur_y * _EDIT_COLS + cur_x] = (u16)' ' | ((u16)_VGA_ATTR << 8);
        }
        
        // Handle Enter Key
        else if (c == '\n') {
            if (cur_y < _EDIT_ROWS - 1) {
                cur_y++;
                cur_x = 0;
            }
        }
        
        // Handle Printable ASCII Characters
        else if (c >= 32 && c <= 126) {
            text_buf[cur_y * _EDIT_COLS + cur_x] = c;
            vga[cur_y * _EDIT_COLS + cur_x] = (u16)c | ((u16)_VGA_ATTR << 8);

            cur_x++;
            if (cur_x >= _EDIT_COLS) {
                cur_x = 0;
                if (cur_y < _EDIT_ROWS - 1) {
                    cur_y++;
                }
            }
        }

        editor_draw_status(filename, cur_x, cur_y);
    }

    // --- FAT32 Persistent Write back ---
    if (mounted_bpb != NULL) {
        // Compute actual payload size ignoring trailing whitespace
        u32 payload_len = _EDIT_BUF_SIZE;
        while (payload_len > 0 && text_buf[payload_len - 1] == ' ') {
            payload_len--;
        }

        // Create file directory record if it does not exist
        fat32_add_entry(current_dir_cluster, filename, 0x00, 0, 0);

        vfs_node_t *target_node = fat32_finddir(vfs_root, filename);
        if (target_node) {
            fat32_write(target_node, 0, payload_len, (u8 *)text_buf);
            kfree(target_node);
        }
    }

    kfree(text_buf);

    // Wipe VGA screen and restore bish prompt state
    extern long unsigned int cursor_pos;
    cursor_pos = 0;
    for (int i = 0; i < _EDIT_COLS * 25; i++) {
        vga[i] = (u16)' ' | ((u16)_VGA_ATTR << 8);
    }

    vga_puts("[ URBUFFER ] File saved successfully: ");
    vga_puts(filename);
    vga_puts("\n\n");
}

//main kernel function
void kmain(u32 memory_entries_count, MemoryMapEntry* mmap_entries)
{
	serial_init();     // Ready the serial interface
	pit_init(1000);    // Configure timer ticks to 1ms
	idt_init();        // Set up interrupt handlers silently
	pic_remap();       // Remap PIC away from CPU exception vectors

	// Unmask required hardware interrupt lines
	outb(_PIC1_DATA, 0xF0); // Open Timer (IRQ0), Keyboard (IRQ1), COM1 (IRQ4)
	outb(_PIC2_DATA, 0xEF); // Open Mouse (IRQ12)

	// Bring the kernel to life globally!
	__asm__("sti");

	// Flush old keyboard controller trailing bytes safely
	while (inb(0x64) & 1) {
		inb(0x60);
	}

	serial_puts("Silent core initialization successful. Booting UI...\n");

	vga_puts("UROS KERNEL v1.0.0 (uroskrnl.bin)\n");
	vga_puts("Copyright (c) 2026 Ugwu Rhema.\n");
	vga_puts("\n");
	sleep(100);
	vga_puts("[ OK ] - Initializing GDT and system descriptors...\n");
	sleep(100);
	vga_puts("[ OK ] - Interrupt Descriptor Table (IDT) loaded.\n");
	sleep(100);
	vga_puts("[ OK ] - PIC successfully remapped. Vector offsets: 0x20 / 0x28.\n");
	sleep(100);
	vga_puts("[ INFO ] - Initializing peripheral driver models...\n");
	mouse_init();
	sleep(100);
	vga_puts("[ OK ] - Serial COM1 port driver active.\n");
	sleep(100);
	vga_puts("[ OK ] - i8042 PS/2 Keyboard driver active.\n");
	sleep(100);
	vga_puts("[ OK ] - PS/2 Mouse driver pointer subsystem active.\n");
	sleep(100);
	vga_puts("[ INFO ] - Setting up Physical Memory Management (PMM). \n");
	sleep(100);
	vga_puts("[ INFO ] - Memory Map active. \n");
	sleep(100);
	//start up the monolithic allocator...
	pmm_init(memory_entries_count, mmap_entries);
	vga_puts("[ OK ] - PMM Monolithic Allocator Active. \n");
	sleep(100);
	vga_puts("[ INFO ] - Constructing kernel tables and activating paging. \n");
	sleep(100);
	vmm_init();
	vga_puts("[ OK ] - Virtual Memory Manager (VMM) Active. Paging Enabled. \n");
	sleep(100);
	vga_puts("[ INFO ] - Shaping out Kernel Heap Space. \n");
	sleep(100);
	kheap_init(32);	//map a 128 KB initail heap space (32 pages)
	vga_puts("[ OK ] - Kernel Heap Active (kmalloc & kfree enabled). \n");
	sleep(100);
	vga_puts("[ INFO ] - Probing peripheral controller storage indexes... \n");
	sleep(100);

	int disk_detected = ata_identify_slave();
	int use_hardware_storage = 0;

	if (disk_detected)
	{
		while (buffer_pop() != 0);

		while (inb(0x64) & 1)
		{
			inb(0x60);
		}

		vga_puts("Mount detected storage drive as primary storage system? (y/n): ");
		char choice = 0;
		while (choice == 0)
		{
			__asm__ volatile("hlt"); //put CPU to sleep...
			choice = buffer_pop(); //check if a character was pushed into the buffer...
		}

		vga_put_c(choice);
		vga_puts("\n");

		if (choice == 'y' || choice == 'Y')
		{
			use_hardware_storage = 1;
		}
	} else {
		vga_puts("[ INFO ] - No secondary hardware connected to storage ports. \n");
		sleep(200);
	}

	vga_puts("[ INFO ] - Initializing Virtual File System tree layers. \n");
	sleep(200);

	vfs_init(use_hardware_storage);
	sleep(200);

	vga_puts("\nSetting of all essesntials done, Launching user session in 5 seconds...\n");
	sleep(5000);


	//CLI here broski....
	//clear screen...
	cursor_pos = 0;
	volatile u16 *vga = (volatile u16 *)_VGA_ADDRESS;
    for (int i = 0; i < _VGA_COLS * _VGA_ROWS; i++) {
        vga[i] = (u16)' ' | ((u16)_VGA_ATTR << 8);
    }

    vga_puts("Welcome to the UROS SHELL(Unrestricted Runtime Operating System)\n");
    vga_puts("Type 'help' for a list of helpful commands\n");

    cmd_fetch();

	//initail prompt
	vga_puts("@root:uros:");
	vga_puts(current_working_dir);
	vga_puts("> ");

	memset(shell_buffer, 0, _SHELL_BUFFER_SIZE);

	while (1)
	{
		char c = buffer_pop();

		if (c != 0)
		{
			//Handle enter key...
			if (c == '\n')
			{
				vga_put_c('\n');

				shell_buffer[shell_index] = '\0'; //null-terminate the string

				//command parser...
				if (shell_index > 0)
				{
					if (strcmp(shell_buffer, "help") == 0)
					{
						vga_puts("Commands currently available: \n\n");
						vga_puts("help| exit | whereami | urfetch | clear | ping | wifi| mem\n");
						vga_puts("mmap| whoami| alloc_test | mock cat| ls | pwd | cd <dir>\n");
						vga_puts("touch <filename>| poweroff | vm reboot | mkdir <dirname>\n");
                        vga_puts("buffer <filename>\n");
					} else if (strcmp(shell_buffer, "clear") == 0){
						// Quick screen clear: reset cursor and wipe VGA memory space
                    	extern long unsigned int cursor_pos;
                     	cursor_pos = 0;
                      	volatile u16 *vga = (volatile u16 *)0xB8000;
                       	for (int i = 0; i < 80 * 25; i++) {
                        	vga[i] = (u16)' ' | ((u16)0x0E << 8);
                        }
					} else if (strcmp(shell_buffer, "ping") == 0){
						vga_puts("pong!\n");
					} else if (strcmp(shell_buffer, "whoami") == 0){
						vga_puts("root\n");
					} else if (strcmp(shell_buffer, "mmap") == 0){
						vga_puts("Type: 1=Usable RAM | 2=Reserved Hardware\n");
						vga_puts("BASE-ADDRESS------LENGTH------TYPE\n");
						vga_puts("__________________________________\n");

						u32 lines_printed = 0;

						for (u32 i = 0; i < memory_entries_count; ++i)
						{
							if (lines_printed > 0 && lines_printed % 10 == 0)
							{
								vga_puts("\n-- Press ANY key for entries --");

								while (buffer_pop() != 0);

								char wait_char = 0;
								while (wait_char == 0)
								{
									__asm__ volatile("hlt"); //rest CPU safely
									wait_char = buffer_pop();
								}

								for (int b = 0; b < 31; b++)
								{
									vga_put_c('\b');
								}
							}
							//prints base address
							vga_put_hex((u32)mmap_entries[i].base_address);
							vga_puts("------");

							//prints length
							vga_put_hex((u32)mmap_entries[i].length);
							vga_puts("------");

							if (mmap_entries[i].type == 1)
							{
								vga_puts("1 (Usable)\n");
							} else {
								vga_puts("2 (Reserved)\n");
							}

							lines_printed++;
						}
					} else if (strcmp(shell_buffer, "mem") == 0){
						u32 actual_free_blocks = 0;

					    // Manually count the actual 0 bits
					    for (u32 i = 0; i < max_blocks; i++) {
					        if (!bitmap_test(i)) {
					            actual_free_blocks++;
					        }
					    }

					    u32 free_mb = actual_free_blocks / 256;
					    u32 total_mb = max_blocks / 256;

					    vga_puts("PMM Stats:\n");
					    vga_puts("  Total Tracked Address Space: ");
					    vga_put_num(total_mb);
					    vga_puts(" MB\n");

					    vga_puts("  Actual Free Usable RAM:      ");
					    vga_put_num(free_mb);
					    vga_puts(" MB\n");
					} else if (str_has_prefix(shell_buffer, "mkdir ")){
					    const char* dir_name = shell_buffer + 6;
                        //skip extra spaces...
                        while (*dir_name == ' ') dir_name++;

                        if (*dir_name == '\0')
                        {
                            vga_puts("Usage: mkdir <dir_name>\n");
                        } else {
                            if (fat32_create_dir(current_dir_cluster, dir_name))
                            {
                                vga_puts("\n");
                            } else {
                                vga_puts("\n");
                            }
                        }
					} else if (str_has_prefix(shell_buffer, "buffer ")){
                        const char *filename = shell_buffer + 5;
                        cmd_buffer(filename);
                    } else if (strcmp(shell_buffer, "ls") == 0){
						vga_puts("Directory listing for context: ");
						vga_puts(current_working_dir);
						vga_puts("\n");
						cmd_ls(current_dir_cluster);
					} else if (shell_buffer[0] == 't' && shell_buffer[1] == 'o' && shell_buffer[2] == 'u' && shell_buffer[3] == 'c' && shell_buffer[4] == 'h' && shell_buffer[5] == ' '){
						//touch command
						const char* filename = &shell_buffer[6];
						cmd_touch(filename);
					} else if (shell_buffer[0] == 'c' && shell_buffer[1] == 'a' && shell_buffer[2] == 't' && shell_buffer[3] == ' '){
						//cat command
					    const char* file_path = &shell_buffer[4];

					    // Build the absolute path for VFS
					    char abs_path[256];
					    int ap_idx = 0;

					    if (file_path[0] != '/') {
					        // Prepend the current working directory string
					        int c_idx = 0;
					        while (current_working_dir[c_idx] != '\0') {
					            abs_path[ap_idx++] = current_working_dir[c_idx++];
					        }
					        // Append the target file name
					        int f_idx = 0;
					        while (file_path[f_idx] != '\0') {
					            abs_path[ap_idx++] = file_path[f_idx++];
					        }
					        abs_path[ap_idx] = '\0';
					    } else {
					        // Path is already absolute
					        int f_idx = 0;
					        while (file_path[f_idx] != '\0') {
					            abs_path[ap_idx++] = file_path[f_idx++];
					        }
					        abs_path[ap_idx] = '\0';
					    }

					    vga_puts("Reading path: ");
					    vga_puts(abs_path);
					    vga_puts("\n");

					    // Walk abstract tree node down from active VFS layout anchor
					    struct vfs_node *target_node = vfs_find_path(vfs_root, abs_path);

					    if (target_node != NULL && target_node->type == _VFS_FILE)
					    {
					        // Dynamically allocate a buffer sized perfectly to the target file
					        u8 *read_buffer = (u8*)kmalloc(target_node->size + 1);
					        if (read_buffer)
					        {
					            vfs_read(target_node, 0, target_node->size, read_buffer);
					            read_buffer[target_node->size] = '\0'; // Enforce safe layout boundaries

					            vga_puts((char*)read_buffer);
					            vga_puts("\n");
					            kfree(read_buffer);
					        }
					        kfree(target_node); // Free VFS container wrapper safely
					    } else {
					        vga_puts("[ ERROR ] - Could not track file node down path.\n");
						}
					} else if (strcmp(shell_buffer, "pwd") == 0 || strcmp(shell_buffer, "whereami") == 0){
						cmd_pwd();
					} else if (shell_buffer[0] == 'c' && shell_buffer[1] == 'd' && shell_buffer[2] == ' '){
						const char* target_path = &shell_buffer[3];
						cmd_cd(target_path);
					} else if (shell_buffer[0] == 's' && shell_buffer[1] == 'l' && shell_buffer[2] == 'e' && shell_buffer[3] == 'e' && shell_buffer[4] == 'p' && shell_buffer[5] == ' '){
						char *t_milliseconds = &shell_buffer[6];
						u32 milliseconds = string_to_int(t_milliseconds);
						vga_puts("Sleeping for ");
						vga_put_num(milliseconds / 1000);
						vga_puts(" seconds...\n");
						sleep(milliseconds);
					} else if (shell_buffer[0] == 'e' && shell_buffer[1] == 'c' && shell_buffer[2] == 'h' && shell_buffer[3] == 'o' && shell_buffer[4] == ' '){
						if (shell_buffer[5] == '\0') vga_puts("Usage: echo <text>\n");
						const char* string  = &shell_buffer[5];
						vga_puts(string);
						vga_puts("\n");
					} else if (strcmp(shell_buffer, "urfetch") == 0){
						cmd_fetch();
					} else if (strcmp(shell_buffer, "wifi") == 0){
						vga_puts("wifi connected\n");
					} else if (strcmp(shell_buffer, "exit") == 0 || strcmp(shell_buffer, "poweroff") == 0){
						vga_puts("Shutting down UROS safely...\n");
						serial_puts("Shutdown command executed via CLI. Halting system.\n");

						// 1. Wait a moment for visual feedback
						sleep(1000);

						// 2. Try QEMU/Emulator explicit shutdown ports
						qemu_shutdown();

						// 3. Fallback: If running on real hardware (where port 0x604 does nothing),
						// turn off interrupts and lock the CPU in a dead loop so it's safe to power off.
						vga_puts("It is now safe to turn off your computer.\n");
						__asm__ volatile("cli"); // Disable interrupts so the clock timer stops waking it up
						while(1) {
							__asm__ volatile("hlt"); // Put CPU into deep sleep forever
						}
					} else if (strcmp(shell_buffer, "vm reboot") == 0){
                        vga_puts("\nRESTARTING...\n");
                        sleep(2000);
                        outb(0x64, 0xFE);
                    } else if (strcmp(shell_buffer, "cd") == 0){
                        vga_puts("cd: Wrong Usage\n");
                        vga_puts("usage: cd <directory>\n");
                    } else if (strcmp(shell_buffer, "alloc-test") == 0){
						vga_puts("Testing Heap...Allocating Memory blocks:\n");
						sleep(1000);

						char *ptr1 = (char*)kmalloc(128);
						char *ptr2 = (char*)kmalloc(128);

						vga_puts("  Block 1 Allocated at address: 0x");
						vga_put_num((u32)ptr1);
						vga_puts("\n");

						vga_puts("  Block 2 Allocated at address: 0x");
						vga_put_num((u32)ptr2);
						vga_puts("\n");

						sleep(1000);

						if (ptr1 && ptr2)
						{
							vga_puts("[ OK ] - Splitting and headers intact, freeing...\n");
							kfree(ptr1);
							kfree(ptr2);
							vga_puts("[ SUCCESS ] - Memory freed and Heap Stable. \n");
						} else {
							vga_puts("[ ERROR ] - Allocation failed! Retruned NULL. \n");
						}
					} else if (strcmp(shell_buffer, "mock cat") == 0){
						vga_puts("Resolving path /bin/hello.txt...\n");

						//try to walk down the tree to find the node...
						vfs_node_t *target_node = vfs_find_path(vfs_root, "/bin/hello.txt");

						if (target_node != NULL)
						{
							u8 read_buffer[64];
							for (int i = 0; i < 64; ++i) read_buffer[i] = 0;

							vfs_read(target_node, 0, 60, read_buffer);

							vga_puts("File content: \"");
							vga_puts((char*)read_buffer);
							vga_puts("\"\n");
						} else {
							vga_puts("[ ERROR ] - Could not track down node path. \n");
						}
					} else {
						vga_puts("/bin/ursh: unknown command: ");
						vga_puts(shell_buffer);
						vga_puts("\n");
					}
				}

				//reset shell for next command...
				memset(shell_buffer, 0, _SHELL_BUFFER_SIZE);
				shell_index = 0;

				vga_puts("\n@root:uros:");
				vga_puts(current_working_dir);
				vga_puts("> ");
			} else if (c == '\b'){
				//handle backspace key...
				if (shell_index > 0)
				{
					shell_index--;
					shell_buffer[shell_index] = 0;

					//trigger visual backspace deletion on VGA
					vga_put_c('\b');
                    serial_put_c('\b');
				}
			} else {
				//handle regular characters...
				if (shell_index < _SHELL_BUFFER_SIZE - 1)
				{
					shell_buffer[shell_index] = c;
					shell_index++;

					vga_put_c(c);
					serial_put_c(c);
				}
			}
		}

		__asm__("hlt"); //rest CPU until next interrupt!
	}

	/*//halt the CPU forever after executing instructions...
	is what we would've continued doing until we got our
	keyboard and mouse drivers working, so why don't we make a CLI
	above!
	while(1){
		char c = buffer_pop();
		if (c != 0)
		{
			vga_put_c(c);
			serial_put_c(c);
		}
		__asm__("hlt");
	}
*/
}

//IT WAS PERFECT!
